import { buildStoreUrl } from '@/shared/lib/storeSlug';
import { buildStoreFeatures } from '@/shared/lib/domain/features';
import type { MvpDatabase } from '@/shared/types/models';

const now = new Date();

function isoDaysAgo(daysAgo: number, hours = 9) {
  const value = new Date(now);
  value.setDate(value.getDate() - daysAgo);
  value.setHours(hours, 0, 0, 0);
  return value.toISOString();
}

export function createSeedDatabase(): MvpDatabase {
  const profileId = 'profile_platform_owner';
  const goldenOwnerProfileId = 'profile_golden_owner';
  const mintOwnerProfileId = 'profile_mint_owner';
  const storeA = 'store_golden_coffee';
  const storeB = 'store_mint_bbq';
  const requestGolden = 'request_golden_coffee';
  const requestMint = 'request_mint_bbq';
  const requestAurora = 'request_aurora_brunch';
  const requestNorth = 'request_north_roast';
  const requestEmber = 'request_ember_noodle';
  const requestUrban = 'request_urban_salad';
  const categoryCoffee = 'category_golden_coffee';
  const categoryBakery = 'category_golden_bakery';
  const menuAmericano = 'menu_americano';
  const menuLatte = 'menu_latte';
  const menuCroffle = 'menu_croffle';
  const menuBagel = 'menu_bagel';
  const storeATableA1 = 'table_a1';
  const storeATableA2 = 'table_a2';
  const storeATableB1 = 'table_b1';
  const orderCompleted = 'order_completed_1';
  const orderPreparing = 'order_preparing_1';
  const orderReady = 'order_ready_1';
  const surveyId = 'survey_experience';

  return {
    profiles: [
      {
        id: profileId,
        full_name: 'Platform Owner',
        email: 'ops@mybiz.ai.kr',
        phone: '010-1234-0001',
        created_at: isoDaysAgo(60),
      },
      {
        id: goldenOwnerProfileId,
        full_name: '김민준',
        email: 'golden@example.com',
        phone: '010-2000-1111',
        created_at: isoDaysAgo(92),
      },
      {
        id: mintOwnerProfileId,
        full_name: '이도윤',
        email: 'mint@example.com',
        phone: '010-2000-2222',
        created_at: isoDaysAgo(75),
      },
    ],
    store_requests: [
      {
        id: requestUrban,
        business_name: 'Urban Salad Lab',
        owner_name: '장서희',
        business_number: '998-12-41002',
        phone: '010-9090-1111',
        email: 'urban@example.com',
        address: '서울시 강남구 테헤란로 201',
        business_type: '샐러드',
        requested_slug: 'urban-salad',
        requested_plan: 'starter',
        selected_features: ['order_management', 'table_order', 'sales_analysis'],
        brand_name: 'Urban Salad Lab',
        brand_color: '#16a34a',
        tagline: '오피스 점심 구독을 준비하는 샐러드 바',
        description: '런치 구독과 픽업 주문을 함께 운영하려는 샐러드 전문점 요청입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        directions: '역삼역 3번 출구 도보 4분, 공유오피스 1층 코너 매장 예정',
        menu_preview: [
          { id: 'req_menu_urban_1', category: '샐러드', name: '치킨 케일 샐러드', price: 10900, description: '시그니처 런치 샐러드', is_signature: true },
          { id: 'req_menu_urban_2', category: '랩', name: '그릴드 랩', price: 8900, description: '테이크아웃 중심 대표 메뉴', is_signature: false },
        ],
        notices: [{ id: 'req_notice_urban_1', title: '오픈 예정', content: '7월 초 오픈을 목표로 세팅 요청 중입니다.' }],
        status: 'draft',
        created_at: isoDaysAgo(0, 9),
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: requestAurora,
        business_name: 'Aurora Brunch',
        owner_name: '박서윤',
        business_number: '445-81-90012',
        phone: '010-3030-1221',
        email: 'aurora@example.com',
        address: '서울시 송파구 올림픽로 212',
        business_type: '브런치 카페',
        requested_slug: 'aurora-brunch',
        requested_plan: 'pro',
        selected_features: ['ai_manager', 'customer_management', 'reservation_management', 'sales_analysis', 'order_management', 'table_order'],
        brand_name: 'Aurora Brunch',
        brand_color: '#f97316',
        tagline: '주말 대기와 예약을 함께 운영하는 브런치 스토어',
        description: '브런치 카페 오픈 전 예약/웨이팅/QR 주문 기반 MVP 운영을 희망합니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        directions: '잠실새내역 5번 출구 도보 6분, 대로변 코너 2층',
        menu_preview: [
          { id: 'req_menu_aurora_1', category: '브런치', name: '에그 베네딕트', price: 16800, description: '대표 브런치 메뉴', is_signature: true },
          { id: 'req_menu_aurora_2', category: '음료', name: '오로라 라떼', price: 6900, description: '브랜드 시그니처 음료', is_signature: true },
          { id: 'req_menu_aurora_3', category: '디저트', name: '프렌치 토스트', price: 14800, description: '주말 인기 예상 메뉴', is_signature: false },
        ],
        notices: [
          { id: 'req_notice_aurora_1', title: '반려동물 동반 불가', content: '실내 좌석 운영 정책에 따라 반려동물 동반은 제한됩니다.' },
          { id: 'req_notice_aurora_2', title: '주말 웨이팅 운영', content: '주말 오전 10시 이후 웨이팅 기능 활성화를 요청했습니다.' },
        ],
        status: 'submitted',
        created_at: isoDaysAgo(0, 10),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: requestNorth,
        business_name: 'North Roast',
        owner_name: '최도현',
        business_number: '551-23-77891',
        phone: '010-4040-4556',
        email: 'north@example.com',
        address: '서울시 용산구 한강대로 88',
        business_type: '카페 로스터리',
        requested_slug: 'north-roast',
        requested_plan: 'business',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'brand_management', 'sales_analysis', 'order_management', 'table_order'],
        brand_name: 'North Roast',
        brand_color: '#7c2d12',
        tagline: '원두 구독과 B2B 납품을 함께 운영하는 로스터리',
        description: '브랜드 페이지와 AI 리포트를 포함한 다점포 확장을 준비 중입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80',
        directions: '신용산역 도보 7분, 베이커리 골목 초입',
        menu_preview: [
          { id: 'req_menu_north_1', category: '원두', name: '북로스트 블렌드', price: 18000, description: '200g 홀빈 패키지', is_signature: true },
          { id: 'req_menu_north_2', category: '음료', name: '드립 커피', price: 6500, description: '원두별 추출 메뉴', is_signature: true },
        ],
        notices: [{ id: 'req_notice_north_1', title: '원두 납품 문의 예정', content: '기업 납품용 별도 문의 폼 추가를 요청했습니다.' }],
        status: 'reviewing',
        review_notes: '브랜드 컬러와 B2B 안내 섹션 구성을 검토 중입니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(0, 11),
        created_at: isoDaysAgo(1, 13),
        updated_at: isoDaysAgo(0, 11),
      },
      {
        id: requestGolden,
        business_name: 'Golden Coffee',
        owner_name: '김민준',
        business_number: '123-45-67890',
        phone: '02-1111-2222',
        email: 'golden@example.com',
        address: '서울시 성동구 성수동 123-4',
        business_type: '카페',
        requested_slug: 'golden-coffee',
        requested_plan: 'pro',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'reservation_management', 'schedule_management', 'surveys', 'brand_management', 'sales_analysis', 'order_management', 'waiting_board', 'contracts', 'table_order'],
        brand_name: 'Golden Coffee',
        brand_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
        directions: '성수역 2번 출구 도보 5분, 골목 안쪽 주황색 간판',
        menu_preview: [
          { id: 'req_menu_golden_1', category: '커피', name: '아메리카노', price: 4500, description: '시그니처 블렌드', is_signature: true },
          { id: 'req_menu_golden_2', category: '디저트', name: '크로플', price: 7500, description: '재구매율이 높은 디저트', is_signature: true },
        ],
        notices: [{ id: 'req_notice_golden_1', title: '테이블 간격 안내', content: '주말 피크타임에는 90분 이용 안내를 노출합니다.' }],
        status: 'approved',
        review_notes: '초기 세팅과 QR 주문 구성이 완료되어 운영 중입니다.',
        reviewed_by_email: 'ops@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(88),
        linked_store_id: storeA,
        created_at: isoDaysAgo(95),
        updated_at: isoDaysAgo(88),
      },
      {
        id: requestMint,
        business_name: 'Mint BBQ',
        owner_name: '이도윤',
        business_number: '234-56-78901',
        phone: '02-2222-3333',
        email: 'mint@example.com',
        address: '서울시 마포구 연남동 45-8',
        business_type: '고깃집',
        requested_slug: 'mint-bbq',
        requested_plan: 'business',
        selected_features: ['ai_manager', 'customer_management', 'reservation_management', 'sales_analysis', 'order_management', 'waiting_board', 'table_order'],
        brand_name: 'Mint BBQ',
        brand_color: '#0f766e',
        tagline: '회전율과 웨이팅을 함께 보는 고깃집 운영',
        description: '멀티테넌시 Store Switcher 데모를 위한 보조 스토어입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
        directions: '홍대입구역 3번 출구 도보 8분, 연남 메인거리 골목',
        menu_preview: [{ id: 'req_menu_mint_1', category: '메인', name: '민트 특선 세트', price: 36000, description: '2인 추천 세트', is_signature: true }],
        notices: [{ id: 'req_notice_mint_1', title: '주말 단체 예약 우선', content: '예약관리와 웨이팅보드 연동을 중심으로 운영합니다.' }],
        status: 'approved',
        review_notes: '웨이팅/예약 중심 운영으로 승인 완료되었습니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(70),
        linked_store_id: storeB,
        created_at: isoDaysAgo(78),
        updated_at: isoDaysAgo(70),
      },
      {
        id: requestEmber,
        business_name: 'Ember Noodle Bar',
        owner_name: '강지훈',
        business_number: '110-43-90001',
        phone: '010-5050-7878',
        email: 'ember@example.com',
        address: '서울시 종로구 율곡로 31',
        business_type: '면요리',
        requested_slug: 'ember-noodle',
        requested_plan: 'starter',
        selected_features: ['order_management', 'sales_analysis', 'table_order'],
        brand_name: 'Ember Noodle Bar',
        brand_color: '#b91c1c',
        tagline: '심야 영업 중심의 면요리 바',
        description: '현재는 사업자 정보 보완이 필요해 반려된 요청입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
        directions: '안국역 2번 출구 도보 3분, 야간 상권 밀집 구간',
        menu_preview: [{ id: 'req_menu_ember_1', category: '면요리', name: '매운 탄탄면', price: 9800, description: '대표 메뉴', is_signature: true }],
        notices: [{ id: 'req_notice_ember_1', title: '야간 영업 안내', content: '심야 운영 중심으로 공지 영역 구성을 희망합니다.' }],
        status: 'rejected',
        review_notes: '사업자 등록증 보완과 연락처 재확인이 필요합니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(2, 16),
        created_at: isoDaysAgo(4, 15),
        updated_at: isoDaysAgo(2, 16),
      },
    ],
    stores: [
      {
        id: storeA,
        name: 'Golden Coffee',
        slug: 'golden-coffee',
        owner_name: '김민준',
        business_number: '123-45-67890',
        phone: '02-1111-2222',
        email: 'golden@example.com',
        address: '서울시 성동구 성수동 123-4',
        business_type: '카페',
        logo_url: '',
        brand_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        public_status: 'public',
        subscription_plan: 'pro',
        admin_email: 'golden@example.com',
        created_from_request_id: requestGolden,
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(2),
      },
      {
        id: storeB,
        name: 'Mint BBQ',
        slug: 'mint-bbq',
        owner_name: '이도윤',
        business_number: '234-56-78901',
        phone: '02-2222-3333',
        email: 'mint@example.com',
        address: '서울시 마포구 연남동 45-8',
        business_type: '고깃집',
        logo_url: '',
        brand_color: '#0f766e',
        tagline: '회전율과 웨이팅을 함께 보는 고깃집 운영',
        description: '멀티테넌시 Store Switcher 데모를 위한 보조 스토어입니다.',
        public_status: 'private',
        subscription_plan: 'business',
        admin_email: 'mint@example.com',
        created_from_request_id: requestMint,
        created_at: isoDaysAgo(72),
        updated_at: isoDaysAgo(1),
      },
    ],
    store_brand_profiles: [
      {
        id: 'brand_profile_golden',
        store_id: storeA,
        brand_name: 'Golden Coffee',
        logo_url: '',
        primary_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        updated_at: isoDaysAgo(2),
      },
      {
        id: 'brand_profile_mint',
        store_id: storeB,
        brand_name: 'Mint BBQ',
        logo_url: '',
        primary_color: '#0f766e',
        tagline: '회전율과 웨이팅을 함께 보는 고깃집 운영',
        description: '멀티테넌시 Store Switcher 데모를 위한 보조 스토어입니다.',
        updated_at: isoDaysAgo(1),
      },
    ],
    store_media: [
      {
        id: 'media_golden_hero',
        store_id: storeA,
        type: 'hero',
        title: '대표 이미지',
        image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        caption: '브랜드 대표 썸네일',
        sort_order: 1,
      },
      {
        id: 'media_golden_storefront',
        store_id: storeA,
        type: 'storefront',
        title: '전경 사진',
        image_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80',
        caption: '성수동 외부 전경',
        sort_order: 2,
      },
      {
        id: 'media_golden_interior',
        store_id: storeA,
        type: 'interior',
        title: '내부 사진',
        image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
        caption: '테이블 좌석 중심 내부 전경',
        sort_order: 3,
      },
      {
        id: 'media_mint_hero',
        store_id: storeB,
        type: 'hero',
        title: '대표 이미지',
        image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
        caption: '민트BBQ 대표 이미지',
        sort_order: 1,
      },
      {
        id: 'media_mint_storefront',
        store_id: storeB,
        type: 'storefront',
        title: '전경 사진',
        image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        caption: '연남동 외부 전경',
        sort_order: 2,
      },
      {
        id: 'media_mint_interior',
        store_id: storeB,
        type: 'interior',
        title: '내부 사진',
        image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
        caption: '대기/좌석 동선이 보이는 내부',
        sort_order: 3,
      },
    ],
    store_locations: [
      {
        id: 'location_golden',
        store_id: storeA,
        address: '서울시 성동구 성수동 123-4',
        directions: '성수역 2번 출구 도보 5분, 오렌지 컬러 간판이 보이는 골목 초입',
        parking_note: '근처 공영주차장 이용',
        published: true,
      },
      {
        id: 'location_mint',
        store_id: storeB,
        address: '서울시 마포구 연남동 45-8',
        directions: '홍대입구역 3번 출구 도보 8분, 연남 메인거리 골목 안쪽',
        parking_note: '주차 공간 없음',
        published: false,
      },
    ],
    store_notices: [
      {
        id: 'notice_golden_1',
        store_id: storeA,
        title: '주말 90분 이용 안내',
        content: '주말 피크타임에는 테이블 회전율 확보를 위해 90분 이용 안내를 노출합니다.',
        is_pinned: true,
        published_at: isoDaysAgo(2),
      },
      {
        id: 'notice_mint_1',
        store_id: storeB,
        title: '단체 예약 우선 안내',
        content: '웨이팅보드와 예약관리를 연동해 단체 고객 우선 입장을 준비 중입니다.',
        is_pinned: true,
        published_at: isoDaysAgo(1),
      },
    ],
    store_members: [
      {
        id: 'member_store_a',
        store_id: storeA,
        profile_id: goldenOwnerProfileId,
        role: 'owner',
        created_at: isoDaysAgo(90),
      },
      {
        id: 'member_store_b',
        store_id: storeB,
        profile_id: mintOwnerProfileId,
        role: 'owner',
        created_at: isoDaysAgo(72),
      },
    ],
    store_features: [
      ...buildStoreFeatures(storeA, [
        'ai_manager',
        'ai_business_report',
        'customer_management',
        'reservation_management',
        'schedule_management',
        'surveys',
        'brand_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'contracts',
        'table_order',
      ]),
      ...buildStoreFeatures(storeB, [
        'ai_manager',
        'customer_management',
        'reservation_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'table_order',
      ]),
    ],
    store_tables: [
      {
        id: storeATableA1,
        store_id: storeA,
        table_no: 'A1',
        seats: 2,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A1`,
        is_active: true,
      },
      {
        id: storeATableA2,
        store_id: storeA,
        table_no: 'A2',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A2`,
        is_active: true,
      },
      {
        id: storeATableB1,
        store_id: storeA,
        table_no: 'B1',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=B1`,
        is_active: true,
      },
      {
        id: 'table_mint_t1',
        store_id: storeB,
        table_no: 'T1',
        seats: 6,
        qr_value: `${buildStoreUrl('mint-bbq')}/order?table=T1`,
        is_active: true,
      },
    ],
    menu_categories: [
      { id: categoryCoffee, store_id: storeA, name: '커피', sort_order: 1 },
      { id: categoryBakery, store_id: storeA, name: '푸드', sort_order: 2 },
      { id: 'category_mint_meat', store_id: storeB, name: '메인', sort_order: 1 },
    ],
    menu_items: [
      {
        id: menuAmericano,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '아메리카노',
        price: 4500,
        description: '골든커피 시그니처 블렌드',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuLatte,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '카페라떼',
        price: 5200,
        description: '우유 밸런스가 좋은 라떼',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuCroffle,
        store_id: storeA,
        category_id: categoryBakery,
        name: '크로플',
        price: 7500,
        description: '단골 구매율이 높은 디저트',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBagel,
        store_id: storeA,
        category_id: categoryBakery,
        name: '바질 베이글',
        price: 6800,
        description: '부진 메뉴 후보',
        is_popular: false,
        is_active: true,
      },
      {
        id: 'menu_mint_combo',
        store_id: storeB,
        category_id: 'category_mint_meat',
        name: '민트 특선 세트',
        price: 36000,
        description: '2인 추천 세트',
        is_popular: true,
        is_active: true,
      },
    ],
    customers: [
      {
        id: 'customer_hana',
        store_id: storeA,
        name: '김하나',
        phone: '010-1111-1111',
        email: 'hana@example.com',
        visit_count: 5,
        last_visit_at: isoDaysAgo(1),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(40),
      },
      {
        id: 'customer_minho',
        store_id: storeA,
        name: '박민호',
        phone: '010-2222-2222',
        email: 'minho@example.com',
        visit_count: 2,
        last_visit_at: isoDaysAgo(5),
        is_regular: false,
        marketing_opt_in: false,
        created_at: isoDaysAgo(12),
      },
      {
        id: 'customer_sujin',
        store_id: storeA,
        name: '이수진',
        phone: '010-7777-7777',
        email: 'sujin@example.com',
        visit_count: 7,
        last_visit_at: isoDaysAgo(0, 10),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(90),
      },
    ],
    orders: [
      {
        id: orderCompleted,
        store_id: storeA,
        customer_id: 'customer_hana',
        table_id: storeATableA1,
        table_no: 'A1',
        channel: 'table',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 12000,
        placed_at: isoDaysAgo(0, 11),
        completed_at: isoDaysAgo(0, 11),
        note: '얼음 적게',
      },
      {
        id: orderPreparing,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'preparing',
        payment_status: 'pending',
        total_amount: 10400,
        placed_at: isoDaysAgo(0, 12),
        note: '빨대 없이',
      },
      {
        id: orderReady,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'ready',
        payment_status: 'pending',
        total_amount: 7500,
        placed_at: isoDaysAgo(0, 13),
      },
      {
        id: 'order_delivery_1',
        store_id: storeA,
        customer_id: 'customer_minho',
        channel: 'delivery',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 15600,
        placed_at: isoDaysAgo(1, 18),
        completed_at: isoDaysAgo(1, 18),
      },
      {
        id: 'order_walkin_1',
        store_id: storeA,
        channel: 'walk_in',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 9700,
        placed_at: isoDaysAgo(2, 9),
        completed_at: isoDaysAgo(2, 9),
      },
      {
        id: 'order_reservation_1',
        store_id: storeA,
        customer_id: 'customer_sujin',
        table_id: storeATableB1,
        table_no: 'B1',
        channel: 'reservation',
        status: 'accepted',
        payment_status: 'pending',
        total_amount: 18800,
        placed_at: isoDaysAgo(0, 17),
        note: '예약 고객 선주문',
      },
    ],
    order_items: [
      {
        id: 'order_item_1',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 4500,
        line_total: 4500,
      },
      {
        id: 'order_item_2',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_3',
        order_id: orderPreparing,
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_4',
        order_id: orderReady,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_5',
        order_id: 'order_delivery_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 3,
        unit_price: 5200,
        line_total: 15600,
      },
      {
        id: 'order_item_6',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
      {
        id: 'order_item_7',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 2900,
        line_total: 2900,
      },
      {
        id: 'order_item_8',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_9',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
    ],
    kitchen_tickets: [
      {
        id: 'ticket_order_preparing',
        store_id: storeA,
        order_id: orderPreparing,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'preparing',
        created_at: isoDaysAgo(0, 12),
        updated_at: isoDaysAgo(0, 12),
      },
      {
        id: 'ticket_order_ready',
        store_id: storeA,
        order_id: orderReady,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'ready',
        created_at: isoDaysAgo(0, 13),
        updated_at: isoDaysAgo(0, 13),
      },
    ],
    reservations: [
      {
        id: 'reservation_1',
        store_id: storeA,
        customer_name: '최서윤',
        phone: '010-3333-3333',
        party_size: 2,
        reserved_at: isoDaysAgo(0, 18),
        status: 'booked',
      },
      {
        id: 'reservation_2',
        store_id: storeA,
        customer_name: '유지호',
        phone: '010-4444-4444',
        party_size: 4,
        reserved_at: isoDaysAgo(1, 13),
        status: 'completed',
      },
      {
        id: 'reservation_3',
        store_id: storeA,
        customer_name: '이수진',
        phone: '010-7777-7777',
        party_size: 3,
        reserved_at: isoDaysAgo(0, 19),
        status: 'seated',
        note: '창가 자리 선호',
      },
    ],
    waiting_entries: [
      {
        id: 'waiting_1',
        store_id: storeA,
        customer_name: '정다은',
        phone: '010-5555-5555',
        party_size: 2,
        quoted_wait_minutes: 15,
        status: 'waiting',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_2',
        store_id: storeA,
        customer_name: '오준',
        phone: '010-6666-6666',
        party_size: 3,
        quoted_wait_minutes: 5,
        status: 'called',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_3',
        store_id: storeA,
        customer_name: '강도현',
        phone: '010-8888-8888',
        party_size: 4,
        quoted_wait_minutes: 20,
        status: 'waiting',
        created_at: isoDaysAgo(0, 11),
      },
    ],
    surveys: [
      {
        id: surveyId,
        store_id: storeA,
        title: '방문 경험 설문',
        description: '오늘 방문 경험을 빠르게 들려주세요.',
        questions: [
          { id: 'q_rating', label: '전반적인 만족도', type: 'rating' },
          { id: 'q_menu', label: '가장 만족한 메뉴', type: 'text' },
        ],
        is_active: true,
        created_at: isoDaysAgo(7),
      },
    ],
    survey_responses: [
      {
        id: 'survey_response_1',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '김하나',
        rating: 5,
        comment: '좌석 응대가 빨랐어요.',
        answers: [
          { question_id: 'q_rating', value: 5 },
          { question_id: 'q_menu', value: '크로플' },
        ],
        created_at: isoDaysAgo(1),
      },
      {
        id: 'survey_response_2',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '박민호',
        rating: 4,
        comment: '커피 맛이 좋아요.',
        answers: [
          { question_id: 'q_rating', value: 4 },
          { question_id: 'q_menu', value: '아메리카노' },
        ],
        created_at: isoDaysAgo(2),
      },
    ],
    store_schedules: [
      {
        id: 'schedule_shift_1',
        store_id: storeA,
        title: '오픈 준비',
        type: 'shift',
        starts_at: isoDaysAgo(0, 8),
        ends_at: isoDaysAgo(0, 12),
        assignee: '김민준',
      },
      {
        id: 'schedule_meeting_1',
        store_id: storeA,
        title: '주간 메뉴 리뷰',
        type: 'meeting',
        starts_at: isoDaysAgo(0, 16),
        ends_at: isoDaysAgo(0, 17),
        assignee: '매니저',
      },
    ],
    contracts: [
      {
        id: 'contract_1',
        store_id: storeA,
        title: '원두 공급 계약',
        counterparty: '로스터리 B',
        status: 'signed',
        file_url: 'https://example.com/contracts/beans.pdf',
        metadata: {
          signed_by: '김민준',
          memo: '재계약 완료',
        },
        created_at: isoDaysAgo(10),
      },
    ],
    ai_reports: [
      {
        id: 'ai_report_1',
        store_id: storeA,
        report_type: 'daily',
        title: '일간 운영 리포트',
        summary: '오늘 요약: 점심 시간대 테이블 주문 비중이 높고 크로플이 재구매 유도 역할을 했습니다. 인기 메뉴는 크로플, 부진 시간대는 오후 3시 전후이며, 재방문 고객에게 디저트 번들 제안을 검토할 수 있습니다.',
        metrics: {
          todaySales: 12000,
          todayOrders: 3,
        },
        generated_at: isoDaysAgo(0, 14),
        source: 'fallback',
      },
    ],
    sales_daily: [
      {
        id: 'sales_0',
        store_id: storeA,
        sale_date: new Date().toISOString().slice(0, 10),
        order_count: 3,
        total_sales: 41200,
        average_order_value: 13733,
        channel_mix: { table: 2, reservation: 1 },
      },
      {
        id: 'sales_1',
        store_id: storeA,
        sale_date: isoDaysAgo(1).slice(0, 10),
        order_count: 2,
        total_sales: 28600,
        average_order_value: 14300,
        channel_mix: { delivery: 1, table: 1 },
      },
      {
        id: 'sales_2',
        store_id: storeA,
        sale_date: isoDaysAgo(2).slice(0, 10),
        order_count: 2,
        total_sales: 19700,
        average_order_value: 9850,
        channel_mix: { walk_in: 1, table: 1 },
      },
      {
        id: 'sales_3',
        store_id: storeA,
        sale_date: isoDaysAgo(3).slice(0, 10),
        order_count: 4,
        total_sales: 52200,
        average_order_value: 13050,
        channel_mix: { table: 3, delivery: 1 },
      },
      {
        id: 'sales_4',
        store_id: storeA,
        sale_date: isoDaysAgo(4).slice(0, 10),
        order_count: 3,
        total_sales: 34100,
        average_order_value: 11367,
        channel_mix: { table: 2, walk_in: 1 },
      },
      {
        id: 'sales_5',
        store_id: storeA,
        sale_date: isoDaysAgo(5).slice(0, 10),
        order_count: 2,
        total_sales: 21400,
        average_order_value: 10700,
        channel_mix: { delivery: 1, walk_in: 1 },
      },
      {
        id: 'sales_6',
        store_id: storeA,
        sale_date: isoDaysAgo(6).slice(0, 10),
        order_count: 5,
        total_sales: 60800,
        average_order_value: 12160,
        channel_mix: { table: 4, delivery: 1 },
      },
    ],
    billing_records: [
      {
        id: 'billing_golden',
        store_id: storeA,
        admin_email: 'golden@example.com',
        plan: 'pro',
        setup_status: 'setup_paid',
        subscription_status: 'subscription_active',
        last_payment_at: isoDaysAgo(3, 10),
        next_billing_at: isoDaysAgo(-27, 10),
        payment_method_status: 'ready',
        updated_at: isoDaysAgo(0, 10),
        events: [
          {
            id: 'billing_event_golden_setup',
            store_id: storeA,
            event_type: 'setup_fee',
            title: '초기 세팅비 결제 완료',
            amount: 390000,
            status: 'paid',
            occurred_at: isoDaysAgo(89, 11),
          },
          {
            id: 'billing_event_golden_subscription',
            store_id: storeA,
            event_type: 'subscription_charge',
            title: '3월 구독 결제 성공',
            amount: 79000,
            status: 'paid',
            occurred_at: isoDaysAgo(3, 10),
          },
        ],
      },
      {
        id: 'billing_mint',
        store_id: storeB,
        admin_email: 'mint@example.com',
        plan: 'business',
        setup_status: 'setup_paid',
        subscription_status: 'subscription_past_due',
        last_payment_at: isoDaysAgo(34, 10),
        next_billing_at: isoDaysAgo(-2, 9),
        payment_method_status: 'action_required',
        updated_at: isoDaysAgo(0, 9),
        events: [
          {
            id: 'billing_event_mint_setup',
            store_id: storeB,
            event_type: 'setup_fee',
            title: '초기 세팅비 결제 완료',
            amount: 490000,
            status: 'paid',
            occurred_at: isoDaysAgo(71, 9),
          },
          {
            id: 'billing_event_mint_failed',
            store_id: storeB,
            event_type: 'payment_failure',
            title: '정기 결제 실패',
            amount: 149000,
            status: 'failed',
            occurred_at: isoDaysAgo(1, 8),
            note: '카드 유효기간 만료로 재시도 필요',
          },
          {
            id: 'billing_event_mint_refund',
            store_id: storeB,
            event_type: 'refund_request',
            title: '환불/해지 문의 접수',
            amount: 149000,
            status: 'requested',
            occurred_at: isoDaysAgo(0, 8),
            note: '운영 중단 여부 검토 요청',
          },
        ],
      },
    ],
    admin_users: [
      {
        id: 'admin_platform_owner',
        profile_id: profileId,
        name: 'Platform Owner',
        email: 'ops@mybiz.ai.kr',
        role: 'platform_owner',
        linked_store_ids: [storeA, storeB],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(0, 9),
        created_at: isoDaysAgo(60),
      },
      {
        id: 'admin_platform_review',
        name: '리뷰 관리자',
        email: 'review@mybiz.ai.kr',
        role: 'platform_admin',
        linked_store_ids: [],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(0, 8),
        created_at: isoDaysAgo(45),
      },
      {
        id: 'admin_golden_owner',
        profile_id: goldenOwnerProfileId,
        name: '김민준',
        email: 'golden@example.com',
        role: 'store_owner',
        linked_store_ids: [storeA],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(1, 18),
        created_at: isoDaysAgo(92),
      },
      {
        id: 'admin_mint_owner',
        profile_id: mintOwnerProfileId,
        name: '이도윤',
        email: 'mint@example.com',
        role: 'store_manager',
        linked_store_ids: [storeB],
        status: 'pending',
        invitation_status: 'sent',
        last_sign_in_at: isoDaysAgo(5, 12),
        created_at: isoDaysAgo(75),
      },
      {
        id: 'admin_aurora_candidate',
        name: '박서윤',
        email: 'aurora@example.com',
        role: 'store_owner',
        linked_store_ids: [],
        status: 'pending',
        invitation_status: 'scheduled',
        created_at: isoDaysAgo(0, 10),
      },
    ],
    system_status: [
      {
        id: 'system_data_source',
        key: 'data_source',
        label: '현재 데이터 소스',
        value: 'Mock Repository Active',
        status: 'active',
        description: 'mock/local storage 기반 데이터 저장소가 운영 콘솔에 연결되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_gemini',
        key: 'gemini',
        label: 'Gemini 상태',
        value: 'Gemini Fallback Enabled',
        status: 'ready',
        description: 'AI 응답 실패 시 fallback narrative를 사용하도록 준비되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_portone',
        key: 'portone',
        label: 'PortOne 연동 준비 상태',
        value: 'PortOne Billing Pending Integration',
        status: 'pending',
        description: 'billing 탭에서 세팅비/구독/환불 상태를 먼저 운영하고 향후 PortOne 웹훅으로 확장할 예정입니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_public_pages',
        key: 'public_pages',
        label: '공개 페이지 상태',
        value: 'Public Pages Ready',
        status: 'active',
        description: '홈페이지, 요금제, 약관/개인정보/환불 페이지가 공개 라우트로 준비되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_admin_console',
        key: 'admin_console',
        label: '보호 라우트 상태',
        value: 'Admin Console Active',
        status: 'active',
        description: '/dashboard 이하 경로는 보호 라우트로 분리되어 dev 관리자 콘솔로 동작합니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_seed',
        key: 'seed_state',
        label: '최근 배포/시드 상태',
        value: 'Seed Refreshed 2026-03-14',
        status: 'ready',
        description: '스토어 요청, billing, admin users, system status seed가 최신 기준으로 반영되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
    ],
    store_provisioning_logs: [
      {
        id: 'log_golden_requested',
        request_id: requestGolden,
        store_id: storeA,
        action: 'requested',
        level: 'info',
        message: '골든커피 스토어 생성 요청이 접수되었습니다.',
        created_at: isoDaysAgo(95, 9),
      },
      {
        id: 'log_golden_approved',
        request_id: requestGolden,
        store_id: storeA,
        action: 'approved',
        level: 'success',
        message: '검수 완료 후 운영 스토어로 승인되었습니다.',
        created_at: isoDaysAgo(88, 11),
      },
      {
        id: 'log_golden_store_created',
        request_id: requestGolden,
        store_id: storeA,
        action: 'store_created',
        level: 'success',
        message: 'stores, brand, location, notices, features가 생성되었습니다.',
        created_at: isoDaysAgo(88, 11),
      },
      {
        id: 'log_mint_requested',
        request_id: requestMint,
        store_id: storeB,
        action: 'requested',
        level: 'info',
        message: '민트BBQ 스토어 생성 요청이 접수되었습니다.',
        created_at: isoDaysAgo(78, 9),
      },
      {
        id: 'log_mint_billing',
        request_id: requestMint,
        store_id: storeB,
        action: 'billing_created',
        level: 'success',
        message: '초기 세팅비 billing record가 생성되었습니다.',
        created_at: isoDaysAgo(71, 11),
      },
      {
        id: 'log_north_review',
        request_id: requestNorth,
        action: 'review_started',
        level: 'info',
        message: '브랜드 컬러, B2B 섹션, 멀티매장 운영 범위를 검토 중입니다.',
        created_at: isoDaysAgo(0, 11),
      },
      {
        id: 'log_ember_rejected',
        request_id: requestEmber,
        action: 'rejected',
        level: 'warning',
        message: '사업자 정보 보완 요청으로 반려 처리되었습니다.',
        created_at: isoDaysAgo(2, 16),
      },
    ],
  };
}
