import { buildStoreUrl } from '@/shared/lib/storeSlug';
import { buildStoreFeatures } from '@/shared/lib/domain/features';
import type { MvpDatabase } from '@/shared/types/models';

const now = new Date();

function isoDaysAgo(daysAgo: number, hours = 9) {
  const value = new Date(now);
  value.setDate(value.getDate() - daysAgo);
  value.setHours(hours, 0, 0, 0);
  return value.toISOString();
}

export function createSeedDatabase(): MvpDatabase {
  const profileId = 'profile_demo_owner';
  const storeA = 'store_golden_coffee';
  const storeB = 'store_mint_bbq';
  const categoryCoffee = 'category_golden_coffee';
  const categoryBakery = 'category_golden_bakery';
  const menuAmericano = 'menu_americano';
  const menuLatte = 'menu_latte';
  const menuCroffle = 'menu_croffle';
  const menuBagel = 'menu_bagel';
  const storeATableA1 = 'table_a1';
  const storeATableA2 = 'table_a2';
  const storeATableB1 = 'table_b1';
  const orderCompleted = 'order_completed_1';
  const orderPreparing = 'order_preparing_1';
  const orderReady = 'order_ready_1';
  const surveyId = 'survey_experience';

  return {
    profiles: [
      {
        id: profileId,
        full_name: 'Demo Owner',
        email: 'owner@mybiz.ai.kr',
        phone: '010-1234-0001',
        created_at: isoDaysAgo(60),
      },
    ],
    store_setup_requests: [],
    stores: [
      {
        id: storeA,
        name: 'Golden Coffee',
        slug: 'golden-coffee',
        owner_name: '김민준',
        business_number: '123-45-67890',
        phone: '02-1111-2222',
        email: 'golden@example.com',
        address: '서울시 성동구 성수동 123-4',
        business_type: '카페',
        logo_url: '',
        brand_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(2),
      },
      {
        id: storeB,
        name: 'Mint BBQ',
        slug: 'mint-bbq',
        owner_name: '이도윤',
        business_number: '234-56-78901',
        phone: '02-2222-3333',
        email: 'mint@example.com',
        address: '서울시 마포구 연남동 45-8',
        business_type: '고깃집',
        logo_url: '',
        brand_color: '#0f766e',
        tagline: '회전율과 웨이팅을 함께 보는 고깃집 운영',
        description: '멀티테넌시 Store Switcher 데모를 위한 보조 스토어입니다.',
        created_at: isoDaysAgo(72),
        updated_at: isoDaysAgo(1),
      },
    ],
    store_members: [
      {
        id: 'member_store_a',
        store_id: storeA,
        profile_id: profileId,
        role: 'owner',
        created_at: isoDaysAgo(90),
      },
      {
        id: 'member_store_b',
        store_id: storeB,
        profile_id: profileId,
        role: 'owner',
        created_at: isoDaysAgo(72),
      },
    ],
    store_features: [
      ...buildStoreFeatures(storeA, [
        'ai_manager',
        'ai_business_report',
        'customer_management',
        'reservation_management',
        'schedule_management',
        'surveys',
        'brand_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'contracts',
        'table_order',
      ]),
      ...buildStoreFeatures(storeB, [
        'ai_manager',
        'customer_management',
        'reservation_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'table_order',
      ]),
    ],
    store_tables: [
      {
        id: storeATableA1,
        store_id: storeA,
        table_no: 'A1',
        seats: 2,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A1`,
        is_active: true,
      },
      {
        id: storeATableA2,
        store_id: storeA,
        table_no: 'A2',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A2`,
        is_active: true,
      },
      {
        id: storeATableB1,
        store_id: storeA,
        table_no: 'B1',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=B1`,
        is_active: true,
      },
      {
        id: 'table_mint_t1',
        store_id: storeB,
        table_no: 'T1',
        seats: 6,
        qr_value: `${buildStoreUrl('mint-bbq')}/order?table=T1`,
        is_active: true,
      },
    ],
    menu_categories: [
      { id: categoryCoffee, store_id: storeA, name: '커피', sort_order: 1 },
      { id: categoryBakery, store_id: storeA, name: '푸드', sort_order: 2 },
      { id: 'category_mint_meat', store_id: storeB, name: '메인', sort_order: 1 },
    ],
    menu_items: [
      {
        id: menuAmericano,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '아메리카노',
        price: 4500,
        description: '골든커피 시그니처 블렌드',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuLatte,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '카페라떼',
        price: 5200,
        description: '우유 밸런스가 좋은 라떼',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuCroffle,
        store_id: storeA,
        category_id: categoryBakery,
        name: '크로플',
        price: 7500,
        description: '단골 구매율이 높은 디저트',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBagel,
        store_id: storeA,
        category_id: categoryBakery,
        name: '바질 베이글',
        price: 6800,
        description: '부진 메뉴 후보',
        is_popular: false,
        is_active: true,
      },
      {
        id: 'menu_mint_combo',
        store_id: storeB,
        category_id: 'category_mint_meat',
        name: '민트 특선 세트',
        price: 36000,
        description: '2인 추천 세트',
        is_popular: true,
        is_active: true,
      },
    ],
    customers: [
      {
        id: 'customer_hana',
        store_id: storeA,
        name: '김하나',
        phone: '010-1111-1111',
        email: 'hana@example.com',
        visit_count: 5,
        last_visit_at: isoDaysAgo(1),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(40),
      },
      {
        id: 'customer_minho',
        store_id: storeA,
        name: '박민호',
        phone: '010-2222-2222',
        email: 'minho@example.com',
        visit_count: 2,
        last_visit_at: isoDaysAgo(5),
        is_regular: false,
        marketing_opt_in: false,
        created_at: isoDaysAgo(12),
      },
      {
        id: 'customer_sujin',
        store_id: storeA,
        name: '이수진',
        phone: '010-7777-7777',
        email: 'sujin@example.com',
        visit_count: 7,
        last_visit_at: isoDaysAgo(0, 10),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(90),
      },
    ],
    orders: [
      {
        id: orderCompleted,
        store_id: storeA,
        customer_id: 'customer_hana',
        table_id: storeATableA1,
        table_no: 'A1',
        channel: 'table',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 12000,
        placed_at: isoDaysAgo(0, 11),
        completed_at: isoDaysAgo(0, 11),
        note: '얼음 적게',
      },
      {
        id: orderPreparing,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'preparing',
        payment_status: 'pending',
        total_amount: 10400,
        placed_at: isoDaysAgo(0, 12),
        note: '빨대 없이',
      },
      {
        id: orderReady,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'ready',
        payment_status: 'pending',
        total_amount: 7500,
        placed_at: isoDaysAgo(0, 13),
      },
      {
        id: 'order_delivery_1',
        store_id: storeA,
        customer_id: 'customer_minho',
        channel: 'delivery',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 15600,
        placed_at: isoDaysAgo(1, 18),
        completed_at: isoDaysAgo(1, 18),
      },
      {
        id: 'order_walkin_1',
        store_id: storeA,
        channel: 'walk_in',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 9700,
        placed_at: isoDaysAgo(2, 9),
        completed_at: isoDaysAgo(2, 9),
      },
      {
        id: 'order_reservation_1',
        store_id: storeA,
        customer_id: 'customer_sujin',
        table_id: storeATableB1,
        table_no: 'B1',
        channel: 'reservation',
        status: 'accepted',
        payment_status: 'pending',
        total_amount: 18800,
        placed_at: isoDaysAgo(0, 17),
        note: '예약 고객 선주문',
      },
    ],
    order_items: [
      {
        id: 'order_item_1',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 4500,
        line_total: 4500,
      },
      {
        id: 'order_item_2',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_3',
        order_id: orderPreparing,
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_4',
        order_id: orderReady,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_5',
        order_id: 'order_delivery_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 3,
        unit_price: 5200,
        line_total: 15600,
      },
      {
        id: 'order_item_6',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
      {
        id: 'order_item_7',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 2900,
        line_total: 2900,
      },
      {
        id: 'order_item_8',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_9',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
    ],
    kitchen_tickets: [
      {
        id: 'ticket_order_preparing',
        store_id: storeA,
        order_id: orderPreparing,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'preparing',
        created_at: isoDaysAgo(0, 12),
        updated_at: isoDaysAgo(0, 12),
      },
      {
        id: 'ticket_order_ready',
        store_id: storeA,
        order_id: orderReady,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'ready',
        created_at: isoDaysAgo(0, 13),
        updated_at: isoDaysAgo(0, 13),
      },
    ],
    reservations: [
      {
        id: 'reservation_1',
        store_id: storeA,
        customer_name: '최서윤',
        phone: '010-3333-3333',
        party_size: 2,
        reserved_at: isoDaysAgo(0, 18),
        status: 'booked',
      },
      {
        id: 'reservation_2',
        store_id: storeA,
        customer_name: '유지호',
        phone: '010-4444-4444',
        party_size: 4,
        reserved_at: isoDaysAgo(1, 13),
        status: 'completed',
      },
      {
        id: 'reservation_3',
        store_id: storeA,
        customer_name: '이수진',
        phone: '010-7777-7777',
        party_size: 3,
        reserved_at: isoDaysAgo(0, 19),
        status: 'seated',
        note: '창가 자리 선호',
      },
    ],
    waiting_entries: [
      {
        id: 'waiting_1',
        store_id: storeA,
        customer_name: '정다은',
        phone: '010-5555-5555',
        party_size: 2,
        quoted_wait_minutes: 15,
        status: 'waiting',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_2',
        store_id: storeA,
        customer_name: '오준',
        phone: '010-6666-6666',
        party_size: 3,
        quoted_wait_minutes: 5,
        status: 'called',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_3',
        store_id: storeA,
        customer_name: '강도현',
        phone: '010-8888-8888',
        party_size: 4,
        quoted_wait_minutes: 20,
        status: 'waiting',
        created_at: isoDaysAgo(0, 11),
      },
    ],
    surveys: [
      {
        id: surveyId,
        store_id: storeA,
        title: '방문 경험 설문',
        description: '오늘 방문 경험을 빠르게 들려주세요.',
        questions: [
          { id: 'q_rating', label: '전반적인 만족도', type: 'rating' },
          { id: 'q_menu', label: '가장 만족한 메뉴', type: 'text' },
        ],
        is_active: true,
        created_at: isoDaysAgo(7),
      },
    ],
    survey_responses: [
      {
        id: 'survey_response_1',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '김하나',
        rating: 5,
        comment: '좌석 응대가 빨랐어요.',
        answers: [
          { question_id: 'q_rating', value: 5 },
          { question_id: 'q_menu', value: '크로플' },
        ],
        created_at: isoDaysAgo(1),
      },
      {
        id: 'survey_response_2',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '박민호',
        rating: 4,
        comment: '커피 맛이 좋아요.',
        answers: [
          { question_id: 'q_rating', value: 4 },
          { question_id: 'q_menu', value: '아메리카노' },
        ],
        created_at: isoDaysAgo(2),
      },
    ],
    store_schedules: [
      {
        id: 'schedule_shift_1',
        store_id: storeA,
        title: '오픈 준비',
        type: 'shift',
        starts_at: isoDaysAgo(0, 8),
        ends_at: isoDaysAgo(0, 12),
        assignee: '김민준',
      },
      {
        id: 'schedule_meeting_1',
        store_id: storeA,
        title: '주간 메뉴 리뷰',
        type: 'meeting',
        starts_at: isoDaysAgo(0, 16),
        ends_at: isoDaysAgo(0, 17),
        assignee: '매니저',
      },
    ],
    contracts: [
      {
        id: 'contract_1',
        store_id: storeA,
        title: '원두 공급 계약',
        counterparty: '로스터리 B',
        status: 'signed',
        file_url: 'https://example.com/contracts/beans.pdf',
        metadata: {
          signed_by: '김민준',
          memo: '재계약 완료',
        },
        created_at: isoDaysAgo(10),
      },
    ],
    ai_reports: [
      {
        id: 'ai_report_1',
        store_id: storeA,
        report_type: 'daily',
        title: '일간 운영 리포트',
        summary: '오늘 요약: 점심 시간대 테이블 주문 비중이 높고 크로플이 재구매 유도 역할을 했습니다. 인기 메뉴는 크로플, 부진 시간대는 오후 3시 전후이며, 재방문 고객에게 디저트 번들 제안을 검토할 수 있습니다.',
        metrics: {
          todaySales: 12000,
          todayOrders: 3,
        },
        generated_at: isoDaysAgo(0, 14),
        source: 'fallback',
      },
    ],
    sales_daily: [
      {
        id: 'sales_0',
        store_id: storeA,
        sale_date: new Date().toISOString().slice(0, 10),
        order_count: 3,
        total_sales: 41200,
        average_order_value: 13733,
        channel_mix: { table: 2, reservation: 1 },
      },
      {
        id: 'sales_1',
        store_id: storeA,
        sale_date: isoDaysAgo(1).slice(0, 10),
        order_count: 2,
        total_sales: 28600,
        average_order_value: 14300,
        channel_mix: { delivery: 1, table: 1 },
      },
      {
        id: 'sales_2',
        store_id: storeA,
        sale_date: isoDaysAgo(2).slice(0, 10),
        order_count: 2,
        total_sales: 19700,
        average_order_value: 9850,
        channel_mix: { walk_in: 1, table: 1 },
      },
      {
        id: 'sales_3',
        store_id: storeA,
        sale_date: isoDaysAgo(3).slice(0, 10),
        order_count: 4,
        total_sales: 52200,
        average_order_value: 13050,
        channel_mix: { table: 3, delivery: 1 },
      },
      {
        id: 'sales_4',
        store_id: storeA,
        sale_date: isoDaysAgo(4).slice(0, 10),
        order_count: 3,
        total_sales: 34100,
        average_order_value: 11367,
        channel_mix: { table: 2, walk_in: 1 },
      },
      {
        id: 'sales_5',
        store_id: storeA,
        sale_date: isoDaysAgo(5).slice(0, 10),
        order_count: 2,
        total_sales: 21400,
        average_order_value: 10700,
        channel_mix: { delivery: 1, walk_in: 1 },
      },
      {
        id: 'sales_6',
        store_id: storeA,
        sale_date: isoDaysAgo(6).slice(0, 10),
        order_count: 5,
        total_sales: 60800,
        average_order_value: 12160,
        channel_mix: { table: 4, delivery: 1 },
      },
    ],
  };
}
