import { buildStoreUrl } from './storeSlug.js';
import { buildAnalyticsSeedForStores } from './analyticsSeed.js';
import { buildStoreFeatures } from './domain/features.js';
import type { MvpDatabase } from '../types/models';

const now = new Date();

function isoDaysAgo(daysAgo: number, hours = 9) {
  const value = new Date(now);
  value.setDate(value.getDate() - daysAgo);
  value.setHours(hours, 0, 0, 0);
  return value.toISOString();
}

function hasEnabledFeature(
  features: MvpDatabase['store_features'],
  storeId: string,
  key: MvpDatabase['store_features'][number]['feature_key'],
) {
  return features.some((feature) => feature.store_id === storeId && feature.feature_key === key && feature.enabled);
}

function buildSeedStorePublicPages(database: MvpDatabase): MvpDatabase['store_public_pages'] {
  return database.stores.map((store) => {
    const brandConfig = store.brand_config;
    const location = database.store_locations.find((item) => item.store_id === store.id) || null;
    const media = database.store_media.filter((item) => item.store_id === store.id);
    const notices = database.store_notices.filter((item) => item.store_id === store.id);

    return {
      id: `store_public_page_${store.id}`,
      store_id: store.id,
      slug: store.slug,
      brand_name: store.name,
      logo_url: store.logo_url,
      brand_color: store.brand_color,
      tagline: store.tagline,
      description: store.description,
      business_type: brandConfig.business_type,
      phone: brandConfig.phone,
      email: brandConfig.email,
      address: brandConfig.address,
      directions: location?.directions || '',
      opening_hours: location?.opening_hours,
      parking_note: location?.parking_note,
      public_status: store.public_status,
      homepage_visible: store.homepage_visible ?? store.public_status === 'public',
      consultation_enabled: store.consultation_enabled ?? true,
      inquiry_enabled: store.inquiry_enabled ?? true,
      reservation_enabled:
        store.reservation_enabled ?? hasEnabledFeature(database.store_features, store.id, 'reservation_management'),
      order_entry_enabled:
        store.order_entry_enabled ??
        (hasEnabledFeature(database.store_features, store.id, 'table_order') ||
          hasEnabledFeature(database.store_features, store.id, 'order_management')),
      theme_preset: store.theme_preset,
      preview_target: store.preview_target,
      hero_title: store.name,
      hero_subtitle: store.tagline,
      hero_description: store.description,
      primary_cta_label: store.primary_cta_label,
      mobile_cta_label: store.mobile_cta_label,
      cta_config: {},
      content_blocks: [],
      seo_metadata: {
        canonicalUrl: buildStoreUrl(store.slug),
        title: store.name,
      },
      media,
      notices,
      created_at: store.created_at,
      updated_at: store.updated_at,
    };
  });
}

export function createSeedDatabase(): MvpDatabase {
  const profileId = 'profile_platform_owner';
  const goldenOwnerProfileId = 'profile_golden_owner';
  const mintOwnerProfileId = 'profile_mint_owner';
  const buffetOwnerProfileId = 'profile_buffet_owner';
  const storeA = 'store_golden_coffee';
  const storeB = 'store_mint_bbq';
  const storeC = 'store_seoul_buffet';
  const requestGolden = 'request_golden_coffee';
  const requestMint = 'request_mint_bbq';
  const requestBuffet = 'request_seoul_buffet';
  const requestAurora = 'request_aurora_brunch';
  const requestNorth = 'request_north_roast';
  const requestEmber = 'request_ember_noodle';
  const requestUrban = 'request_urban_salad';
  const categoryCoffee = 'category_golden_coffee';
  const categoryBakery = 'category_golden_bakery';
  const categoryBuffetHot = 'category_buffet_hot';
  const categoryBuffetCold = 'category_buffet_cold';
  const menuAmericano = 'menu_americano';
  const menuLatte = 'menu_latte';
  const menuCroffle = 'menu_croffle';
  const menuBagel = 'menu_bagel';
  const menuBuffetGalbi = 'menu_buffet_galbi';
  const menuBuffetJapchae = 'menu_buffet_japchae';
  const menuBuffetDessert = 'menu_buffet_dessert';
  const storeATableA1 = 'table_a1';
  const storeATableA2 = 'table_a2';
  const storeATableB1 = 'table_b1';
  const storeCTableH1 = 'table_buffet_h1';
  const storeCTableH2 = 'table_buffet_h2';
  const orderCompleted = 'order_completed_1';
  const orderPreparing = 'order_preparing_1';
  const orderReady = 'order_ready_1';
  const surveyId = 'survey_experience';
  const surveyPulseId = 'survey_menu_pulse';
  const surveyMintId = 'survey_bbq_service';
  const surveyBuffetId = 'survey_buffet_service';
  const analyticsSeed = buildAnalyticsSeedForStores([
    {
      id: storeA,
      slug: 'golden-coffee',
      business_type: '브런치 카페',
    },
    {
      id: storeB,
      slug: 'mint-izakaya',
      business_type: 'izakaya',
    },
    {
      id: storeC,
      slug: 'seoul-buffet-house',
      business_type: 'korean_buffet',
    },
  ]);

  const database: MvpDatabase = {
    profiles: [
      {
        id: profileId,
        full_name: 'Platform Owner',
        email: 'ops@mybiz.ai.kr',
        phone: '010-1234-0001',
        created_at: isoDaysAgo(60),
      },
      {
        id: goldenOwnerProfileId,
        full_name: '김민준',
        email: 'golden@example.com',
        phone: '010-2000-1111',
        created_at: isoDaysAgo(92),
      },
      {
        id: mintOwnerProfileId,
        full_name: '이도윤',
        email: 'mint@example.com',
        phone: '010-2000-2222',
        created_at: isoDaysAgo(75),
      },
      {
        id: buffetOwnerProfileId,
        full_name: 'Han Sujin',
        email: 'buffet@example.com',
        phone: '010-2000-3333',
        created_at: isoDaysAgo(66),
      },
    ],
    store_requests: [
      {
        id: requestUrban,
        business_name: 'Urban Salad Lab',
        owner_name: '장서희',
        business_number: '998-12-41002',
        phone: '010-9090-1111',
        email: 'urban@example.com',
        address: '서울시 강남구 테헤란로 201',
        business_type: '샐러드',
        requested_slug: 'urban-salad',
        requested_plan: 'free',
        selected_features: ['order_management', 'table_order', 'sales_analysis'],
        brand_name: 'Urban Salad Lab',
        brand_color: '#16a34a',
        tagline: '오피스 점심 구독을 준비하는 샐러드 바',
        description: '런치 구독과 픽업 주문을 함께 운영하려는 샐러드 전문점 요청입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1525351484163-7529414344d8?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        directions: '역삼역 3번 출구 도보 4분, 공유오피스 1층 코너 매장 예정',
        menu_preview: [
          { id: 'req_menu_urban_1', category: '샐러드', name: '치킨 케일 샐러드', price: 10900, description: '시그니처 런치 샐러드', is_signature: true },
          { id: 'req_menu_urban_2', category: '랩', name: '그릴드 랩', price: 8900, description: '테이크아웃 중심 대표 메뉴', is_signature: false },
        ],
        notices: [{ id: 'req_notice_urban_1', title: '오픈 예정', content: '7월 초 오픈을 목표로 세팅 요청 중입니다.' }],
        status: 'draft',
        created_at: isoDaysAgo(1, 18),
        updated_at: isoDaysAgo(1, 18),
      },
      {
        id: requestAurora,
        business_name: 'Aurora Brunch',
        owner_name: '박서윤',
        business_number: '445-81-90012',
        phone: '010-3030-1221',
        email: 'aurora@example.com',
        address: '서울시 송파구 올림픽로 212',
        business_type: '브런치 카페',
        requested_slug: 'aurora-brunch',
        requested_plan: 'pro',
        selected_features: ['ai_manager', 'customer_management', 'reservation_management', 'sales_analysis', 'order_management', 'table_order'],
        brand_name: 'Aurora Brunch',
        brand_color: '#f97316',
        tagline: '주말 대기와 예약을 함께 운영하는 브런치 스토어',
        description: '브런치 카페 오픈 전 예약/웨이팅/QR 주문 기반 MVP 운영을 희망합니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        directions: '잠실새내역 5번 출구 도보 6분, 대로변 코너 2층',
        menu_preview: [
          { id: 'req_menu_aurora_1', category: '브런치', name: '에그 베네딕트', price: 16800, description: '대표 브런치 메뉴', is_signature: true },
          { id: 'req_menu_aurora_2', category: '음료', name: '오로라 라떼', price: 6900, description: '브랜드 시그니처 음료', is_signature: true },
          { id: 'req_menu_aurora_3', category: '디저트', name: '프렌치 토스트', price: 14800, description: '주말 인기 예상 메뉴', is_signature: false },
        ],
        notices: [
          { id: 'req_notice_aurora_1', title: '반려동물 동반 불가', content: '실내 좌석 운영 정책에 따라 반려동물 동반은 제한됩니다.' },
          { id: 'req_notice_aurora_2', title: '주말 웨이팅 운영', content: '주말 오전 10시 이후 웨이팅 기능 활성화를 요청했습니다.' },
        ],
        status: 'submitted',
        created_at: isoDaysAgo(0, 10),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: requestNorth,
        business_name: 'North Roast',
        owner_name: '최도현',
        business_number: '551-23-77891',
        phone: '010-4040-4556',
        email: 'north@example.com',
        address: '서울시 용산구 한강대로 88',
        business_type: '카페 로스터리',
        requested_slug: 'north-roast',
        requested_plan: 'vip',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'brand_management', 'sales_analysis', 'order_management', 'table_order'],
        brand_name: 'North Roast',
        brand_color: '#7c2d12',
        tagline: '원두 구독과 B2B 납품을 함께 운영하는 로스터리',
        description: '브랜드 페이지와 AI 리포트를 포함한 다점포 확장을 준비 중입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1447933601403-0c6688de566e?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?auto=format&fit=crop&w=1200&q=80',
        directions: '신용산역 도보 7분, 베이커리 골목 초입',
        menu_preview: [
          { id: 'req_menu_north_1', category: '원두', name: '북로스트 블렌드', price: 18000, description: '200g 홀빈 패키지', is_signature: true },
          { id: 'req_menu_north_2', category: '음료', name: '드립 커피', price: 6500, description: '원두별 추출 메뉴', is_signature: true },
        ],
        notices: [{ id: 'req_notice_north_1', title: '원두 납품 문의 예정', content: '기업 납품용 별도 문의 폼 추가를 요청했습니다.' }],
        status: 'reviewing',
        review_notes: '브랜드 컬러와 B2B 안내 섹션 구성을 검토 중입니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(0, 11),
        created_at: isoDaysAgo(1, 13),
        updated_at: isoDaysAgo(0, 11),
      },
      {
        id: requestGolden,
        business_name: 'Golden Coffee',
        owner_name: '김민준',
        business_number: '123-45-67890',
        phone: '02-1111-2222',
        email: 'golden@example.com',
        address: '서울시 성동구 성수동 123-4',
        business_type: '카페',
        requested_slug: 'golden-coffee',
        requested_plan: 'pro',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'reservation_management', 'schedule_management', 'surveys', 'brand_management', 'sales_analysis', 'order_management', 'waiting_board', 'contracts', 'table_order'],
        brand_name: 'Golden Coffee',
        brand_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
        directions: '성수역 2번 출구 도보 5분, 골목 안쪽 주황색 간판',
        menu_preview: [
          { id: 'req_menu_golden_1', category: '커피', name: '아메리카노', price: 4500, description: '시그니처 블렌드', is_signature: true },
          { id: 'req_menu_golden_2', category: '디저트', name: '크로플', price: 7500, description: '재구매율이 높은 디저트', is_signature: true },
        ],
        notices: [{ id: 'req_notice_golden_1', title: '테이블 간격 안내', content: '주말 피크타임에는 90분 이용 안내를 노출합니다.' }],
        status: 'approved',
        review_notes: '초기 세팅과 QR 주문 구성이 완료되어 운영 중입니다.',
        reviewed_by_email: 'ops@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(88),
        linked_store_id: storeA,
        created_at: isoDaysAgo(95),
        updated_at: isoDaysAgo(88),
      },
      {
        id: requestMint,
        business_name: 'Mint Izakaya',
        owner_name: '이도윤',
        business_number: '234-56-78901',
        phone: '02-2222-3333',
        email: 'mint@example.com',
        address: '서울시 마포구 연남동 45-8',
        business_type: 'izakaya',
        requested_slug: 'mint-izakaya',
        requested_plan: 'vip',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'reservation_management', 'surveys', 'brand_management', 'sales_analysis', 'order_management', 'waiting_board', 'table_order'],
        brand_name: 'Mint Izakaya',
        brand_color: '#0f766e',
        tagline: '하이브리드 이자카야 데모로 예약, 문의, 운영 메모를 함께 보여줍니다.',
        description: '저녁 시간대 이자카야 시나리오로 공개 대문, CRM 문의 흐름, 주문·설문·수기 데이터 연결을 한 번에 설명하기 위한 데모 스토어입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
        directions: '홍대입구역 3번 출구 도보 8분, 저녁 상권 중심 골목 안쪽',
        menu_preview: [{ id: 'req_menu_mint_1', category: 'Skewers', name: 'Chef skewer set', price: 36000, description: '대표 저녁 데모 메뉴', is_signature: true }],
        notices: [{ id: 'req_notice_mint_1', title: '단체 문의 우선 응대', content: 'CRM 문의와 예약 좌석 배정을 함께 설명하기 좋은 데모 흐름입니다.' }],
        status: 'approved',
        review_notes: '예약, 문의, 저녁 시간대 운영 흐름을 함께 보여주는 이자카야 데모로 승인 완료되었습니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(70),
        linked_store_id: storeB,
        created_at: isoDaysAgo(78),
        updated_at: isoDaysAgo(70),
      },
      {
        id: requestEmber,
        business_name: 'Ember Noodle Bar',
        owner_name: '강지훈',
        business_number: '110-43-90001',
        phone: '010-5050-7878',
        email: 'ember@example.com',
        address: '서울시 종로구 율곡로 31',
        business_type: '면요리',
        requested_slug: 'ember-noodle',
        requested_plan: 'free',
        selected_features: ['order_management', 'sales_analysis', 'table_order'],
        brand_name: 'Ember Noodle Bar',
        brand_color: '#b91c1c',
        tagline: '심야 영업 중심의 면요리 바',
        description: '현재는 사업자 정보 보완이 필요해 반려된 요청입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
        directions: '안국역 2번 출구 도보 3분, 야간 상권 밀집 구간',
        menu_preview: [{ id: 'req_menu_ember_1', category: '면요리', name: '매운 탄탄면', price: 9800, description: '대표 메뉴', is_signature: true }],
        notices: [{ id: 'req_notice_ember_1', title: '야간 영업 안내', content: '심야 운영 중심으로 공지 영역 구성을 희망합니다.' }],
        status: 'rejected',
        review_notes: '사업자 등록증 보완과 연락처 재확인이 필요합니다.',
        reviewed_by_email: 'review@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(2, 16),
        created_at: isoDaysAgo(4, 15),
        updated_at: isoDaysAgo(2, 16),
      },
      {
        id: requestBuffet,
        business_name: 'Seoul Buffet House',
        owner_name: 'Han Sujin',
        business_number: '889-31-45670',
        phone: '010-8080-4545',
        email: 'buffet@example.com',
        address: '서울시 강서구 마곡중앙로 77',
        business_type: 'korean_buffet',
        requested_slug: 'seoul-buffet-house',
        requested_plan: 'vip',
        selected_features: ['ai_manager', 'ai_business_report', 'customer_management', 'surveys', 'brand_management', 'sales_analysis'],
        brand_name: 'Seoul Buffet House',
        brand_color: '#8b5e3c',
        tagline: '설문 중심으로 운영 흐름을 보여주는 가족형 뷔페 데모입니다.',
        description: '공개 스토어, 고객 설문, 운영 메모, AI 운영 분석이 한 흐름으로 이어지는 한식 뷔페 시나리오입니다.',
        hero_image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        storefront_image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
        interior_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        directions: '마곡나루역 1번 출구 도보 6분, 가족 외식 수요가 많은 상가 2층',
        menu_preview: [
          { id: 'req_menu_buffet_1', category: 'Hot buffet', name: 'Galbi grill plate', price: 18900, description: 'Most selected lunch buffet plate', is_signature: true },
          { id: 'req_menu_buffet_2', category: 'Cold buffet', name: 'Seasonal noodle salad', price: 12900, description: 'High-repeat buffet item for families', is_signature: false },
        ],
        notices: [{ id: 'req_notice_buffet_1', title: 'Peak refill guide', content: 'Lunch refill speed and dessert tray visibility are the main owner talking points for this demo store.' }],
        status: 'approved',
        review_notes: 'Approved as the survey-first buffet sales demo scenario.',
        reviewed_by_email: 'ops@mybiz.ai.kr',
        reviewed_at: isoDaysAgo(5, 11),
        linked_store_id: storeC,
        created_at: isoDaysAgo(12, 10),
        updated_at: isoDaysAgo(5, 11),
      },
    ],
    stores: [
      {
        id: storeA,
        name: 'Golden Coffee',
        slug: 'golden-coffee',
        brand_config: {
          owner_name: '김민준',
          business_number: '123-45-67890',
          phone: '02-1111-2222',
          email: 'golden@example.com',
          address: '서울시 성동구 성수동 123-4',
          business_type: '카페',
        },
        owner_name: '김민준',
        business_number: '123-45-67890',
        phone: '02-1111-2222',
        email: 'golden@example.com',
        address: '서울시 성동구 성수동 123-4',
        business_type: '카페',
        logo_url: '',
        brand_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        store_mode: 'order_first',
        data_mode: 'order_survey',
        theme_preset: 'warm',
        primary_cta_label: '오늘 메뉴 보기',
        mobile_cta_label: '테이블 주문',
        preview_target: 'order',
        public_status: 'public',
        subscription_plan: 'pro',
        admin_email: 'golden@example.com',
        created_from_request_id: requestGolden,
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(2),
      },
      {
        id: storeB,
        name: 'Mint Izakaya',
        slug: 'mint-izakaya',
        brand_config: {
          owner_name: 'Lee Doyeon',
          business_number: '234-56-78901',
          phone: '02-2222-3333',
          email: 'mint@example.com',
          address: '서울시 마포구 연남동 45-8',
          business_type: 'izakaya',
        },
        owner_name: 'Lee Doyeon',
        business_number: '234-56-78901',
        phone: '02-2222-3333',
        email: 'mint@example.com',
        address: '서울시 마포구 연남동 45-8',
        business_type: 'izakaya',
        logo_url: '',
        brand_color: '#0f766e',
        tagline: '예약과 문의를 함께 보여주는 저녁형 이자카야 데모입니다.',
        description: '공개 스토어 CTA, CRM 문의 흐름, 주문과 운영 메모를 한 화면에서 설명하기 좋은 이자카야 시나리오입니다.',
        store_mode: 'hybrid',
        data_mode: 'order_survey_manual',
        theme_preset: 'modern',
        primary_cta_label: '저녁 메뉴 보기',
        mobile_cta_label: '문의 남기기',
        preview_target: 'inquiry',
        public_status: 'public',
        subscription_plan: 'vip',
        admin_email: 'mint@example.com',
        created_from_request_id: requestMint,
        created_at: isoDaysAgo(72),
        updated_at: isoDaysAgo(1),
      },
      {
        id: storeC,
        name: 'Seoul Buffet House',
        slug: 'seoul-buffet-house',
        brand_config: {
          owner_name: 'Han Sujin',
          business_number: '889-31-45670',
          phone: '010-8080-4545',
          email: 'buffet@example.com',
          address: '서울시 강서구 마곡중앙로 77',
          business_type: 'korean_buffet',
        },
        owner_name: 'Han Sujin',
        business_number: '889-31-45670',
        phone: '010-8080-4545',
        email: 'buffet@example.com',
        address: '서울시 강서구 마곡중앙로 77',
        business_type: 'korean_buffet',
        logo_url: '',
        brand_color: '#8b5e3c',
        tagline: '설문 기반으로 운영 흐름을 보여주는 가족형 뷔페 데모입니다.',
        description: '공개 화면에서 설문, 운영 메모, AI 운영 리포트로 자연스럽게 이어지는 점주 친화형 뷔페 시나리오입니다.',
        store_mode: 'survey_first',
        data_mode: 'survey_manual',
        theme_preset: 'warm',
        primary_cta_label: '뷔페 의견 남기기',
        mobile_cta_label: '고객 설문 열기',
        preview_target: 'survey',
        public_status: 'public',
        subscription_plan: 'vip',
        admin_email: 'buffet@example.com',
        created_from_request_id: requestBuffet,
        created_at: isoDaysAgo(11),
        updated_at: isoDaysAgo(0, 9),
      },
    ],
    store_analytics_profiles: analyticsSeed.profiles,
    store_subscriptions: [
      {
        id: 'subscription_golden',
        store_id: storeA,
        plan: 'pro',
        status: 'active',
        billing_provider: 'portone',
        current_period_starts_at: isoDaysAgo(33, 10),
        current_period_ends_at: isoDaysAgo(-27, 10),
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(3, 10),
      },
      {
        id: 'subscription_mint',
        store_id: storeB,
        plan: 'vip',
        status: 'past_due',
        billing_provider: 'portone',
        current_period_starts_at: isoDaysAgo(64, 10),
        current_period_ends_at: isoDaysAgo(-2, 9),
        created_at: isoDaysAgo(72),
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'subscription_buffet',
        store_id: storeC,
        plan: 'vip',
        status: 'active',
        billing_provider: 'manual',
        current_period_starts_at: isoDaysAgo(26, 9),
        current_period_ends_at: isoDaysAgo(-4, 9),
        created_at: isoDaysAgo(11),
        updated_at: isoDaysAgo(0, 9),
      },
    ],
    store_brand_profiles: [
      {
        id: 'brand_profile_golden',
        store_id: storeA,
        brand_name: 'Golden Coffee',
        logo_url: '',
        primary_color: '#ec5b13',
        tagline: '데이터로 더 잘 파는 동네 카페',
        description: '골든커피의 운영 지표와 QR 주문 흐름을 확인할 수 있는 데모 스토어입니다.',
        updated_at: isoDaysAgo(2),
      },
      {
        id: 'brand_profile_mint',
        store_id: storeB,
        brand_name: 'Mint Izakaya',
        logo_url: '',
        primary_color: '#0f766e',
        tagline: '예약과 문의를 함께 보여주는 저녁형 이자카야 데모입니다.',
        description: '공개 스토어 CTA, CRM 문의 흐름, 주문과 운영 메모를 한 화면에서 설명하기 좋은 이자카야 시나리오입니다.',
        updated_at: isoDaysAgo(1),
      },
      {
        id: 'brand_profile_buffet',
        store_id: storeC,
        brand_name: 'Seoul Buffet House',
        logo_url: '',
        primary_color: '#8b5e3c',
        tagline: '설문 기반으로 운영 흐름을 보여주는 가족형 뷔페 데모입니다.',
        description: '공개 화면에서 설문, 운영 메모, AI 운영 리포트로 자연스럽게 이어지는 점주 친화형 뷔페 시나리오입니다.',
        updated_at: isoDaysAgo(0, 9),
      },
    ],
    store_media: [
      {
        id: 'media_golden_hero',
        store_id: storeA,
        type: 'hero',
        title: '대표 이미지',
        image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',
        caption: '브랜드 대표 썸네일',
        sort_order: 1,
      },
      {
        id: 'media_golden_storefront',
        store_id: storeA,
        type: 'storefront',
        title: '전경 사진',
        image_url: 'https://images.unsplash.com/photo-1453614512568-c4024d13c247?auto=format&fit=crop&w=1200&q=80',
        caption: '성수동 외부 전경',
        sort_order: 2,
      },
      {
        id: 'media_golden_interior',
        store_id: storeA,
        type: 'interior',
        title: '내부 사진',
        image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=1200&q=80',
        caption: '테이블 좌석 중심 내부 전경',
        sort_order: 3,
      },
      {
        id: 'media_mint_hero',
        store_id: storeB,
        type: 'hero',
        title: '저녁 대표 이미지',
        image_url: 'https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?auto=format&fit=crop&w=1200&q=80',
        caption: '저녁 시간대 이자카야 분위기를 보여주는 대표 이미지입니다.',
        sort_order: 1,
      },
      {
        id: 'media_mint_storefront',
        store_id: storeB,
        type: 'storefront',
        title: '매장 전경',
        image_url: 'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',
        caption: '공개 스토어 첫 화면에서 보여주는 외부 전경입니다.',
        sort_order: 2,
      },
      {
        id: 'media_mint_interior',
        store_id: storeB,
        type: 'interior',
        title: '매장 내부',
        image_url: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?auto=format&fit=crop&w=1200&q=80',
        caption: '예약과 문의 동선을 함께 설명하기 좋은 좌석 배치입니다.',
        sort_order: 3,
      },
      {
        id: 'media_buffet_hero',
        store_id: storeC,
        type: 'hero',
        title: '뷔페 대표 이미지',
        image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',
        caption: '가족 방문 손님에게 뷔페 분위기를 먼저 보여주는 대표 이미지입니다.',
        sort_order: 1,
      },
      {
        id: 'media_buffet_storefront',
        store_id: storeC,
        type: 'storefront',
        title: '뷔페 홀',
        image_url: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=1200&q=80',
        caption: '뷔페 코너와 단체 좌석을 함께 보여주는 전경입니다.',
        sort_order: 2,
      },
      {
        id: 'media_buffet_interior',
        store_id: storeC,
        type: 'interior',
        title: '디저트 코너',
        image_url: 'https://images.unsplash.com/photo-1551024506-0bccd828d307?auto=format&fit=crop&w=1200&q=80',
        caption: '디저트와 리필 코너를 함께 보여주는 안내용 이미지입니다.',
        sort_order: 3,
      },
    ],
    store_locations: [
      {
        id: 'location_golden',
        store_id: storeA,
        address: '서울시 성동구 성수동 123-4',
        directions: '성수역 2번 출구 도보 5분, 오렌지 컬러 간판이 보이는 골목 초입',
        parking_note: '근처 공영주차장 이용',
        published: true,
      },
      {
        id: 'location_mint',
        store_id: storeB,
        address: '서울시 마포구 연남동 45-8',
        directions: '홍대입구역 3번 출구 도보 8분, 저녁 상권 중심 골목 안쪽',
        parking_note: '근처 유료 주차장을 이용해 주세요.',
        published: true,
      },
      {
        id: 'location_buffet',
        store_id: storeC,
        address: '서울시 강서구 마곡중앙로 77',
        directions: '마곡나루역 1번 출구 도보 6분, 가족 외식 수요가 많은 메인 상가 2층',
        parking_note: '상가 주차장을 2시간까지 이용할 수 있습니다.',
        opening_hours: '매일 11:00 - 21:30',
        published: true,
      },
    ],
    store_notices: [
      {
        id: 'notice_golden_1',
        store_id: storeA,
        title: '주말 90분 이용 안내',
        content: '주말 피크타임에는 테이블 회전율 확보를 위해 90분 이용 안내를 노출합니다.',
        is_pinned: true,
        published_at: isoDaysAgo(2),
      },
      {
        id: 'notice_mint_1',
        store_id: storeB,
        title: '단체 문의 우선 안내',
        content: '단체 방문 문의 버튼이 바로 보이도록 구성해 예약 좌석 안내와 후속 응대 흐름을 함께 설명할 수 있습니다.',
        is_pinned: true,
        published_at: isoDaysAgo(1),
      },
      {
        id: 'notice_buffet_1',
        store_id: storeC,
        title: '점심 리필 안내',
        content: '점심 피크 시간에는 리필 속도, 디저트 코너 안내, 가족석 회전 흐름을 먼저 확인해 주세요.',
        is_pinned: true,
        published_at: isoDaysAgo(0, 9),
      },
    ],
    store_members: [
      {
        id: 'member_platform_store_a',
        store_id: storeA,
        profile_id: profileId,
        role: 'owner',
        created_at: isoDaysAgo(60),
      },
      {
        id: 'member_platform_store_b',
        store_id: storeB,
        profile_id: profileId,
        role: 'owner',
        created_at: isoDaysAgo(60),
      },
      {
        id: 'member_platform_store_c',
        store_id: storeC,
        profile_id: profileId,
        role: 'owner',
        created_at: isoDaysAgo(60),
      },
      {
        id: 'member_store_a',
        store_id: storeA,
        profile_id: goldenOwnerProfileId,
        role: 'owner',
        created_at: isoDaysAgo(90),
      },
      {
        id: 'member_store_b',
        store_id: storeB,
        profile_id: mintOwnerProfileId,
        role: 'owner',
        created_at: isoDaysAgo(72),
      },
      {
        id: 'member_store_c',
        store_id: storeC,
        profile_id: buffetOwnerProfileId,
        role: 'owner',
        created_at: isoDaysAgo(11),
      },
    ],
    store_features: [
      ...buildStoreFeatures(storeA, [
        'ai_manager',
        'ai_business_report',
        'customer_management',
        'reservation_management',
        'schedule_management',
        'surveys',
        'brand_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'contracts',
        'table_order',
      ]),
      ...buildStoreFeatures(storeB, [
        'ai_manager',
        'ai_business_report',
        'customer_management',
        'reservation_management',
        'surveys',
        'brand_management',
        'sales_analysis',
        'order_management',
        'waiting_board',
        'table_order',
      ]),
      ...buildStoreFeatures(storeC, ['ai_manager', 'ai_business_report', 'customer_management', 'surveys', 'brand_management', 'sales_analysis']),
    ],
    store_priority_settings: analyticsSeed.prioritySettings,
    store_tables: [
      {
        id: storeATableA1,
        store_id: storeA,
        table_no: 'A1',
        seats: 2,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A1`,
        is_active: true,
      },
      {
        id: storeATableA2,
        store_id: storeA,
        table_no: 'A2',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=A2`,
        is_active: true,
      },
      {
        id: storeATableB1,
        store_id: storeA,
        table_no: 'B1',
        seats: 4,
        qr_value: `${buildStoreUrl('golden-coffee')}/order?table=B1`,
        is_active: true,
      },
      {
        id: 'table_mint_t1',
        store_id: storeB,
        table_no: 'T1',
        seats: 6,
        qr_value: `${buildStoreUrl('mint-izakaya')}/order?table=T1`,
        is_active: true,
      },
      {
        id: storeCTableH1,
        store_id: storeC,
        table_no: 'H1',
        seats: 4,
        qr_value: `${buildStoreUrl('seoul-buffet-house')}/order?table=H1`,
        is_active: true,
      },
      {
        id: storeCTableH2,
        store_id: storeC,
        table_no: 'H2',
        seats: 6,
        qr_value: `${buildStoreUrl('seoul-buffet-house')}/order?table=H2`,
        is_active: true,
      },
    ],
    menu_categories: [
      { id: categoryCoffee, store_id: storeA, name: '커피', sort_order: 1 },
      { id: categoryBakery, store_id: storeA, name: '푸드', sort_order: 2 },
      { id: 'category_mint_meat', store_id: storeB, name: '꼬치 요리', sort_order: 1 },
      { id: categoryBuffetHot, store_id: storeC, name: '따뜻한 메뉴', sort_order: 1 },
      { id: categoryBuffetCold, store_id: storeC, name: '차가운 메뉴', sort_order: 2 },
    ],
    menu_items: [
      {
        id: menuAmericano,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '아메리카노',
        price: 4500,
        description: '골든커피 시그니처 블렌드',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuLatte,
        store_id: storeA,
        category_id: categoryCoffee,
        name: '카페라떼',
        price: 5200,
        description: '우유 밸런스가 좋은 라떼',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuCroffle,
        store_id: storeA,
        category_id: categoryBakery,
        name: '크로플',
        price: 7500,
        description: '단골 구매율이 높은 디저트',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBagel,
        store_id: storeA,
        category_id: categoryBakery,
        name: '바질 베이글',
        price: 6800,
        description: '부진 메뉴 후보',
        is_popular: false,
        is_active: true,
      },
      {
        id: 'menu_mint_combo',
        store_id: storeB,
        category_id: 'category_mint_meat',
        name: '셰프 모둠 꼬치 세트',
        price: 36000,
        description: '저녁 시간에 가장 많이 찾는 대표 모둠 세트입니다.',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBuffetGalbi,
        store_id: storeC,
        category_id: categoryBuffetHot,
        name: '갈비 구이 플레이트',
        price: 18900,
        description: '가족 점심 시간에 가장 많이 담는 인기 메뉴입니다.',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBuffetJapchae,
        store_id: storeC,
        category_id: categoryBuffetHot,
        name: '잡채 리필 볼',
        price: 14900,
        description: '뷔페 만족도에서 자주 언급되는 리필 인기 메뉴입니다.',
        is_popular: true,
        is_active: true,
      },
      {
        id: menuBuffetDessert,
        store_id: storeC,
        category_id: categoryBuffetCold,
        name: '디저트 테이스팅 플레이트',
        price: 7900,
        description: '공개 스토어에서 자주 소개하는 디저트 코너 대표 메뉴입니다.',
        is_popular: false,
        is_active: true,
      },
    ],
    customers: [
      {
        id: 'customer_hana',
        store_id: storeA,
        name: '김하나',
        phone: '010-1111-1111',
        email: 'hana@example.com',
        visit_count: 5,
        last_visit_at: isoDaysAgo(1),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(40),
        updated_at: isoDaysAgo(1),
      },
      {
        id: 'customer_minho',
        store_id: storeA,
        name: '박민호',
        phone: '010-2222-2222',
        email: 'minho@example.com',
        visit_count: 2,
        last_visit_at: isoDaysAgo(5),
        is_regular: false,
        marketing_opt_in: false,
        created_at: isoDaysAgo(12),
        updated_at: isoDaysAgo(5),
      },
      {
        id: 'customer_sujin',
        store_id: storeA,
        name: '이수진',
        phone: '010-7777-7777',
        email: 'sujin@example.com',
        visit_count: 7,
        last_visit_at: isoDaysAgo(0, 10),
        is_regular: true,
        marketing_opt_in: true,
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: 'customer_mint_jiwon',
        store_id: storeB,
        name: '이지원',
        phone: '010-9090-2233',
        email: 'jiwon@example.com',
        visit_count: 1,
        last_visit_at: isoDaysAgo(1, 19),
        is_regular: false,
        marketing_opt_in: true,
        created_at: isoDaysAgo(6, 18),
        updated_at: isoDaysAgo(1, 19),
      },
    ],
    customer_contacts: [
      {
        id: 'customer_contact_hana_phone',
        store_id: storeA,
        customer_id: 'customer_hana',
        type: 'phone',
        value: '010-1111-1111',
        normalized_value: '01011111111',
        is_primary: true,
        is_verified: false,
        created_at: isoDaysAgo(40),
        updated_at: isoDaysAgo(1),
      },
      {
        id: 'customer_contact_hana_email',
        store_id: storeA,
        customer_id: 'customer_hana',
        type: 'email',
        value: 'hana@example.com',
        normalized_value: 'hana@example.com',
        is_primary: false,
        is_verified: false,
        created_at: isoDaysAgo(40),
        updated_at: isoDaysAgo(1),
      },
      {
        id: 'customer_contact_minho_phone',
        store_id: storeA,
        customer_id: 'customer_minho',
        type: 'phone',
        value: '010-2222-2222',
        normalized_value: '01022222222',
        is_primary: true,
        is_verified: false,
        created_at: isoDaysAgo(12),
        updated_at: isoDaysAgo(5),
      },
      {
        id: 'customer_contact_minho_email',
        store_id: storeA,
        customer_id: 'customer_minho',
        type: 'email',
        value: 'minho@example.com',
        normalized_value: 'minho@example.com',
        is_primary: false,
        is_verified: false,
        created_at: isoDaysAgo(12),
        updated_at: isoDaysAgo(5),
      },
      {
        id: 'customer_contact_sujin_phone',
        store_id: storeA,
        customer_id: 'customer_sujin',
        type: 'phone',
        value: '010-7777-7777',
        normalized_value: '01077777777',
        is_primary: true,
        is_verified: false,
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: 'customer_contact_sujin_email',
        store_id: storeA,
        customer_id: 'customer_sujin',
        type: 'email',
        value: 'sujin@example.com',
        normalized_value: 'sujin@example.com',
        is_primary: false,
        is_verified: false,
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: 'customer_contact_mint_jiwon_phone',
        store_id: storeB,
        customer_id: 'customer_mint_jiwon',
        type: 'phone',
        value: '010-9090-2233',
        normalized_value: '01090902233',
        is_primary: true,
        is_verified: false,
        created_at: isoDaysAgo(6, 18),
        updated_at: isoDaysAgo(1, 19),
      },
      {
        id: 'customer_contact_mint_jiwon_email',
        store_id: storeB,
        customer_id: 'customer_mint_jiwon',
        type: 'email',
        value: 'jiwon@example.com',
        normalized_value: 'jiwon@example.com',
        is_primary: false,
        is_verified: false,
        created_at: isoDaysAgo(6, 18),
        updated_at: isoDaysAgo(1, 19),
      },
    ],
    customer_preferences: [
      {
        id: 'customer_preference_hana',
        store_id: storeA,
        customer_id: 'customer_hana',
        marketing_opt_in: true,
        preferred_contact_channel: 'sms',
        seating_notes: '창가 좌석 선호',
        dietary_notes: '',
        preference_tags: ['regular', 'coffee'],
        created_at: isoDaysAgo(40),
        updated_at: isoDaysAgo(1),
      },
      {
        id: 'customer_preference_minho',
        store_id: storeA,
        customer_id: 'customer_minho',
        marketing_opt_in: false,
        preferred_contact_channel: 'phone',
        seating_notes: '',
        dietary_notes: '',
        preference_tags: ['delivery'],
        created_at: isoDaysAgo(12),
        updated_at: isoDaysAgo(5),
      },
      {
        id: 'customer_preference_sujin',
        store_id: storeA,
        customer_id: 'customer_sujin',
        marketing_opt_in: true,
        preferred_contact_channel: 'sms',
        seating_notes: '단체 방문 잦음',
        dietary_notes: '',
        preference_tags: ['group-booking', 'high-value'],
        created_at: isoDaysAgo(90),
        updated_at: isoDaysAgo(0, 10),
      },
      {
        id: 'customer_preference_mint_jiwon',
        store_id: storeB,
        customer_id: 'customer_mint_jiwon',
        marketing_opt_in: true,
        preferred_contact_channel: 'sms',
        seating_notes: '',
        dietary_notes: '',
        preference_tags: ['izakaya'],
        created_at: isoDaysAgo(6, 18),
        updated_at: isoDaysAgo(1, 19),
      },
    ],
    customer_timeline_events: [
      {
        id: 'customer_timeline_hana_created',
        store_id: storeA,
        customer_id: 'customer_hana',
        event_type: 'customer_created',
        source: 'demo_seed',
        summary: '단골 고객 기본 카드가 생성되었습니다.',
        metadata: {
          normalizedPhone: '01011111111',
        },
        occurred_at: isoDaysAgo(40),
        created_at: isoDaysAgo(40),
      },
      {
        id: 'customer_timeline_hana_order',
        store_id: storeA,
        customer_id: 'customer_hana',
        event_type: 'order_linked',
        source: 'demo_seed',
        summary: '최근 테이블 주문이 고객 메모리에 연결되었습니다.',
        metadata: {
          orderId: orderCompleted,
        },
        occurred_at: isoDaysAgo(0, 11),
        created_at: isoDaysAgo(0, 11),
      },
      {
        id: 'customer_timeline_sujin_inquiry',
        store_id: storeA,
        customer_id: 'customer_sujin',
        event_type: 'inquiry_captured',
        source: 'demo_seed',
        summary: '단체 예약 문의가 고객 이력에 추가되었습니다.',
        metadata: {
          inquiryId: 'inquiry_golden_group',
        },
        occurred_at: isoDaysAgo(0, 10),
        created_at: isoDaysAgo(0, 10),
      },
      {
        id: 'customer_timeline_mint_jiwon_inquiry',
        store_id: storeB,
        customer_id: 'customer_mint_jiwon',
        event_type: 'inquiry_captured',
        source: 'demo_seed',
        summary: '이자카야 단체 문의가 고객 메모리에 기록되었습니다.',
        metadata: {
          inquiryId: 'inquiry_mint_group',
        },
        occurred_at: isoDaysAgo(1, 18),
        created_at: isoDaysAgo(1, 18),
      },
    ],
    inquiries: [
      {
        id: 'inquiry_golden_group',
        store_id: storeA,
        customer_id: 'customer_sujin',
        customer_name: '이수진',
        phone: '010-7777-7777',
        email: 'sujin@example.com',
        category: 'reservation',
        status: 'in_progress',
        message: '다음 주 토요일 아침 모임 8인 예약이 가능한지 문의드립니다.',
        tags: ['단체', '주말'],
        memo: '창가 좌석 요청. 오전 10시 이후 연락 예정.',
        marketing_opt_in: true,
        requested_visit_date: new Date().toISOString().slice(0, 10),
        source: 'public_form',
        created_at: isoDaysAgo(0, 10),
        updated_at: isoDaysAgo(0, 11),
      },
      {
        id: 'inquiry_golden_brand',
        store_id: storeA,
        customer_name: '박민호',
        phone: '010-2222-2222',
        email: 'minho@example.com',
        category: 'brand',
        status: 'new',
        message: '사무실 케이터링과 브랜드 콜라보 문의를 남깁니다.',
        tags: ['브랜드', '케이터링'],
        memo: '',
        marketing_opt_in: false,
        source: 'public_form',
        created_at: isoDaysAgo(1, 16),
        updated_at: isoDaysAgo(1, 16),
      },
      {
        id: 'inquiry_mint_group',
        store_id: storeB,
        customer_id: 'customer_mint_jiwon',
        customer_name: '이지원',
        phone: '010-9090-2233',
        email: 'jiwon@example.com',
        category: 'group_booking',
        status: 'on_hold',
        message: '다음 주 금요일 저녁 12인 모임 예약 가능 여부와 세트 메뉴를 알고 싶습니다.',
        tags: ['12인', '저녁'],
        memo: '예산 확인 후 재연락 요청.',
        marketing_opt_in: true,
        requested_visit_date: new Date().toISOString().slice(0, 10),
        source: 'public_form',
        created_at: isoDaysAgo(1, 18),
        updated_at: isoDaysAgo(1, 18),
      },
    ],
    conversation_sessions: [],
    conversation_messages: [],
    visitor_sessions: [],
    orders: [
      {
        id: orderCompleted,
        store_id: storeA,
        customer_id: 'customer_hana',
        table_id: storeATableA1,
        table_no: 'A1',
        channel: 'table',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 12000,
        placed_at: isoDaysAgo(0, 11),
        completed_at: isoDaysAgo(0, 11),
        note: '얼음 적게',
      },
      {
        id: orderPreparing,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'preparing',
        payment_status: 'pending',
        total_amount: 10400,
        placed_at: isoDaysAgo(0, 12),
        note: '빨대 없이',
      },
      {
        id: orderReady,
        store_id: storeA,
        table_id: storeATableA2,
        table_no: 'A2',
        channel: 'table',
        status: 'ready',
        payment_status: 'pending',
        total_amount: 7500,
        placed_at: isoDaysAgo(0, 13),
      },
      {
        id: 'order_delivery_1',
        store_id: storeA,
        customer_id: 'customer_minho',
        channel: 'delivery',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 15600,
        placed_at: isoDaysAgo(1, 18),
        completed_at: isoDaysAgo(1, 18),
      },
      {
        id: 'order_walkin_1',
        store_id: storeA,
        channel: 'walk_in',
        status: 'completed',
        payment_status: 'paid',
        total_amount: 9700,
        placed_at: isoDaysAgo(2, 9),
        completed_at: isoDaysAgo(2, 9),
      },
      {
        id: 'order_reservation_1',
        store_id: storeA,
        customer_id: 'customer_sujin',
        table_id: storeATableB1,
        table_no: 'B1',
        channel: 'reservation',
        status: 'accepted',
        payment_status: 'pending',
        total_amount: 18800,
        placed_at: isoDaysAgo(0, 17),
        note: '예약 고객 선주문',
      },
    ],
    order_items: [
      {
        id: 'order_item_1',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 4500,
        line_total: 4500,
      },
      {
        id: 'order_item_2',
        order_id: orderCompleted,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_3',
        order_id: orderPreparing,
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_4',
        order_id: orderReady,
        store_id: storeA,
        menu_item_id: menuCroffle,
        menu_name: '크로플',
        quantity: 1,
        unit_price: 7500,
        line_total: 7500,
      },
      {
        id: 'order_item_5',
        order_id: 'order_delivery_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 3,
        unit_price: 5200,
        line_total: 15600,
      },
      {
        id: 'order_item_6',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
      {
        id: 'order_item_7',
        order_id: 'order_walkin_1',
        store_id: storeA,
        menu_item_id: menuAmericano,
        menu_name: '아메리카노',
        quantity: 1,
        unit_price: 2900,
        line_total: 2900,
      },
      {
        id: 'order_item_8',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuLatte,
        menu_name: '카페라떼',
        quantity: 2,
        unit_price: 5200,
        line_total: 10400,
      },
      {
        id: 'order_item_9',
        order_id: 'order_reservation_1',
        store_id: storeA,
        menu_item_id: menuBagel,
        menu_name: '바질 베이글',
        quantity: 1,
        unit_price: 6800,
        line_total: 6800,
      },
    ],
    kitchen_tickets: [
      {
        id: 'ticket_order_preparing',
        store_id: storeA,
        order_id: orderPreparing,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'preparing',
        created_at: isoDaysAgo(0, 12),
        updated_at: isoDaysAgo(0, 12),
      },
      {
        id: 'ticket_order_ready',
        store_id: storeA,
        order_id: orderReady,
        table_id: storeATableA2,
        table_no: 'A2',
        status: 'ready',
        created_at: isoDaysAgo(0, 13),
        updated_at: isoDaysAgo(0, 13),
      },
    ],
    reservations: [
      {
        id: 'reservation_1',
        store_id: storeA,
        customer_name: '최서윤',
        phone: '010-3333-3333',
        party_size: 2,
        reserved_at: isoDaysAgo(0, 18),
        status: 'booked',
      },
      {
        id: 'reservation_2',
        store_id: storeA,
        customer_name: '유지호',
        phone: '010-4444-4444',
        party_size: 4,
        reserved_at: isoDaysAgo(1, 13),
        status: 'completed',
      },
      {
        id: 'reservation_3',
        store_id: storeA,
        customer_name: '이수진',
        phone: '010-7777-7777',
        party_size: 3,
        reserved_at: isoDaysAgo(0, 19),
        status: 'seated',
        note: '창가 자리 선호',
      },
    ],
    waiting_entries: [
      {
        id: 'waiting_1',
        store_id: storeA,
        customer_name: '정다은',
        phone: '010-5555-5555',
        party_size: 2,
        quoted_wait_minutes: 15,
        status: 'waiting',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_2',
        store_id: storeA,
        customer_name: '오준',
        phone: '010-6666-6666',
        party_size: 3,
        quoted_wait_minutes: 5,
        status: 'called',
        created_at: isoDaysAgo(0, 12),
      },
      {
        id: 'waiting_3',
        store_id: storeA,
        customer_name: '강도현',
        phone: '010-8888-8888',
        party_size: 4,
        quoted_wait_minutes: 20,
        status: 'waiting',
        created_at: isoDaysAgo(0, 11),
      },
    ],
    surveys: [
      {
        id: surveyId,
        store_id: storeA,
        title: '방문 경험 설문',
        description: '오늘 방문 경험을 빠르게 들려주세요.',
        questions: [
          { id: 'q_rating', label: '전반적인 만족도', type: 'rating' },
          { id: 'q_menu', label: '가장 만족한 메뉴', type: 'text' },
        ],
        is_active: true,
        created_at: isoDaysAgo(7),
      },
      {
        id: surveyPulseId,
        store_id: storeA,
        title: '방문 경험 빠른 설문',
        description: '공개 매장 반응과 AI 운영 분석에 함께 쓰는 고객 의견 설문입니다.',
        questions: [
          {
            id: 'q_rating_v2',
            label: '오늘 방문은 전반적으로 만족스러우셨나요?',
            type: 'rating',
            description: '점주 화면에서 바로 확인하는 기본 만족도 점수입니다.',
            required: true,
            sort_order: 1,
          },
          {
            id: 'q_focus_v2',
            label: '오늘 가장 기억에 남은 부분은 무엇이었나요?',
            type: 'single_choice',
            required: true,
            options: ['커피 맛', '베이커리', '좌석 편안함', '직원 응대'],
            sort_order: 2,
          },
          {
            id: 'q_revisit_v2',
            label: '이번 주 안에 다시 방문하고 싶으신가요?',
            type: 'revisit_intent',
            required: true,
            sort_order: 3,
          },
          {
            id: 'q_note_v2',
            label: '다음 방문 전에 보완되면 좋을 점이 있나요?',
            type: 'text',
            required: false,
            sort_order: 4,
            placeholder: '짧게 의견을 남겨 주세요.',
          },
        ],
        is_active: true,
        created_at: isoDaysAgo(1, 8),
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: surveyMintId,
        store_id: storeB,
        title: '저녁 서비스 체크',
        description: '이자카야 저녁 운영 흐름을 확인하는 고객 의견 설문입니다.',
        questions: [
          {
            id: 'q_bbq_rating',
            label: '오늘 저녁 이용 흐름은 만족스러우셨나요?',
            type: 'rating',
            required: true,
            sort_order: 1,
          },
          {
            id: 'q_bbq_team',
            label: '특히 좋았던 부분은 무엇이었나요?',
            type: 'multiple_choice',
            required: false,
            options: ['메뉴 품질', '사이드 메뉴', '좌석 응대', '예약 좌석 안내'],
            sort_order: 2,
          },
          {
            id: 'q_bbq_revisit',
            label: '다음에도 저녁 모임으로 다시 방문하고 싶으신가요?',
            type: 'revisit_intent',
            required: true,
            sort_order: 3,
          },
          {
            id: 'q_bbq_note',
            label: '가장 먼저 보완되면 좋을 점이 있다면 알려주세요.',
            type: 'text',
            required: false,
            sort_order: 4,
            placeholder: '구체적인 의견을 남겨 주세요.',
          },
        ],
        is_active: true,
        created_at: isoDaysAgo(2, 19),
        updated_at: isoDaysAgo(0, 8),
      },
      {
        id: surveyBuffetId,
        store_id: storeC,
        title: '가족 방문 만족도 설문',
        description: '리필 속도, 디저트 안내, 가족석 이용감을 확인하는 고객 의견 설문입니다.',
        questions: [
          {
            id: 'q_buffet_rating',
            label: '오늘 뷔페 이용 흐름은 만족스러우셨나요?',
            type: 'rating',
            required: true,
            sort_order: 1,
          },
          {
            id: 'q_buffet_focus',
            label: '가장 신경 써 주면 좋겠는 부분은 무엇이었나요?',
            type: 'single_choice',
            required: true,
            options: ['리필 속도', '디저트 안내', '가족석 편안함', '안내 표지'],
            sort_order: 2,
          },
          {
            id: 'q_buffet_revisit',
            label: '이번 달 안에 가족과 다시 방문하고 싶으신가요?',
            type: 'revisit_intent',
            required: true,
            sort_order: 3,
          },
          {
            id: 'q_buffet_note',
            label: '가장 먼저 보완되면 좋을 점을 적어 주세요.',
            type: 'text',
            required: false,
            sort_order: 4,
            placeholder: '점주에게 남기고 싶은 의견을 적어 주세요.',
          },
        ],
        is_active: true,
        created_at: isoDaysAgo(1, 10),
        updated_at: isoDaysAgo(0, 10),
      },
    ],
    survey_responses: [
      {
        id: 'survey_response_1',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '김하나',
        rating: 5,
        comment: '좌석 응대가 빨랐어요.',
        answers: [
          { question_id: 'q_rating', value: 5 },
          { question_id: 'q_menu', value: '크로플' },
        ],
        created_at: isoDaysAgo(1),
      },
      {
        id: 'survey_response_2',
        store_id: storeA,
        survey_id: surveyId,
        customer_name: '박민호',
        rating: 4,
        comment: '커피 맛이 좋아요.',
        answers: [
          { question_id: 'q_rating', value: 4 },
          { question_id: 'q_menu', value: '아메리카노' },
        ],
        created_at: isoDaysAgo(2),
      },
      {
        id: 'survey_response_3',
        store_id: storeA,
        survey_id: surveyPulseId,
        customer_name: 'Kim Hana',
        table_code: 'A1',
        rating: 5,
        revisit_intent: 100,
        comment: '좌석 응대가 빨랐고 커피 맛도 깔끔했어요.',
        answers: [
          { question_id: 'q_rating_v2', value: 5 },
          { question_id: 'q_focus_v2', value: '직원 응대' },
          { question_id: 'q_revisit_v2', value: 100 },
          { question_id: 'q_note_v2', value: '베이커리 진열 안내가 조금 더 잘 보이면 좋겠어요.' },
        ],
        created_at: isoDaysAgo(1),
      },
      {
        id: 'survey_response_4',
        store_id: storeA,
        survey_id: surveyPulseId,
        customer_name: 'Park Minho',
        table_code: 'A2',
        rating: 4,
        revisit_intent: 70,
        comment: '라떼가 좋았고 대기 흐름도 매끄러웠어요.',
        answers: [
          { question_id: 'q_rating_v2', value: 4 },
          { question_id: 'q_focus_v2', value: '커피 맛' },
          { question_id: 'q_revisit_v2', value: 70 },
          { question_id: 'q_note_v2', value: '첫 화면에 시그니처 디저트가 하나 더 보이면 좋겠어요.' },
        ],
        created_at: isoDaysAgo(2),
      },
      {
        id: 'survey_response_5',
        store_id: storeB,
        survey_id: surveyMintId,
        customer_name: 'Lee Jiwon',
        table_code: 'T3',
        rating: 5,
        revisit_intent: 100,
        comment: '저녁 타이밍 안내와 사이드 리필이 모두 좋았어요.',
        answers: [
          { question_id: 'q_bbq_rating', value: 5 },
          { question_id: 'q_bbq_team', value: ['메뉴 품질', '사이드 메뉴'] },
          { question_id: 'q_bbq_revisit', value: 100 },
          { question_id: 'q_bbq_note', value: '모바일에서도 예약 좌석 안내가 잘 보이면 좋겠어요.' },
        ],
        created_at: isoDaysAgo(1, 19),
      },
      {
        id: 'survey_response_6',
        store_id: storeC,
        survey_id: surveyBuffetId,
        customer_name: 'Choi Jina',
        table_code: 'H1',
        rating: 4,
        revisit_intent: 80,
        comment: '리필은 빨랐지만 디저트 안내가 조금 더 잘 보이면 좋겠어요.',
        answers: [
          { question_id: 'q_buffet_rating', value: 4 },
          { question_id: 'q_buffet_focus', value: '디저트 안내' },
          { question_id: 'q_buffet_revisit', value: 80 },
          { question_id: 'q_buffet_note', value: '디저트 안내판이 코너 가까이에 있으면 더 좋겠어요.' },
        ],
        created_at: isoDaysAgo(1, 13),
      },
      {
        id: 'survey_response_7',
        store_id: storeC,
        survey_id: surveyBuffetId,
        customer_name: 'Yoon Seho',
        table_code: 'H2',
        rating: 5,
        revisit_intent: 100,
        comment: '가족석이 편했고 따뜻한 메뉴 코너도 계속 잘 채워져 있었어요.',
        answers: [
          { question_id: 'q_buffet_rating', value: 5 },
          { question_id: 'q_buffet_focus', value: '가족석 편안함' },
          { question_id: 'q_buffet_revisit', value: 100 },
          { question_id: 'q_buffet_note', value: '입구 쪽에도 리필 안내가 보이면 좋겠어요.' },
        ],
        created_at: isoDaysAgo(2, 12),
      },
    ],
    store_schedules: [
      {
        id: 'schedule_shift_1',
        store_id: storeA,
        title: '오픈 준비',
        type: 'shift',
        starts_at: isoDaysAgo(0, 8),
        ends_at: isoDaysAgo(0, 12),
        assignee: '김민준',
      },
      {
        id: 'schedule_meeting_1',
        store_id: storeA,
        title: '주간 메뉴 리뷰',
        type: 'meeting',
        starts_at: isoDaysAgo(0, 16),
        ends_at: isoDaysAgo(0, 17),
        assignee: '매니저',
      },
    ],
    contracts: [
      {
        id: 'contract_1',
        store_id: storeA,
        title: '원두 공급 계약',
        counterparty: '로스터리 B',
        status: 'signed',
        file_url: 'https://example.com/contracts/beans.pdf',
        metadata: {
          signed_by: '김민준',
          memo: '재계약 완료',
        },
        created_at: isoDaysAgo(10),
      },
    ],
    ai_reports: [
      {
        id: 'ai_report_1',
        store_id: storeA,
        report_type: 'daily',
        title: '일간 운영 리포트',
        summary: '오늘 요약: 점심 시간대 테이블 주문 비중이 높고 크로플이 재구매 유도 역할을 했습니다. 인기 메뉴는 크로플, 부진 시간대는 오후 3시 전후이며, 재방문 고객에게 디저트 번들 제안을 검토할 수 있습니다.',
        metrics: {
          todaySales: 12000,
          todayOrders: 3,
        },
        generated_at: isoDaysAgo(0, 14),
        source: 'fallback',
      },
    ],
    diagnosis_sessions: [],
    sales_daily: [
      {
        id: 'sales_0',
        store_id: storeA,
        sale_date: new Date().toISOString().slice(0, 10),
        order_count: 3,
        total_sales: 41200,
        average_order_value: 13733,
        channel_mix: { table: 2, reservation: 1 },
      },
      {
        id: 'sales_1',
        store_id: storeA,
        sale_date: isoDaysAgo(1).slice(0, 10),
        order_count: 2,
        total_sales: 28600,
        average_order_value: 14300,
        channel_mix: { delivery: 1, table: 1 },
      },
      {
        id: 'sales_2',
        store_id: storeA,
        sale_date: isoDaysAgo(2).slice(0, 10),
        order_count: 2,
        total_sales: 19700,
        average_order_value: 9850,
        channel_mix: { walk_in: 1, table: 1 },
      },
      {
        id: 'sales_3',
        store_id: storeA,
        sale_date: isoDaysAgo(3).slice(0, 10),
        order_count: 4,
        total_sales: 52200,
        average_order_value: 13050,
        channel_mix: { table: 3, delivery: 1 },
      },
      {
        id: 'sales_4',
        store_id: storeA,
        sale_date: isoDaysAgo(4).slice(0, 10),
        order_count: 3,
        total_sales: 34100,
        average_order_value: 11367,
        channel_mix: { table: 2, walk_in: 1 },
      },
      {
        id: 'sales_5',
        store_id: storeA,
        sale_date: isoDaysAgo(5).slice(0, 10),
        order_count: 2,
        total_sales: 21400,
        average_order_value: 10700,
        channel_mix: { delivery: 1, walk_in: 1 },
      },
      {
        id: 'sales_6',
        store_id: storeA,
        sale_date: isoDaysAgo(6).slice(0, 10),
        order_count: 5,
        total_sales: 60800,
        average_order_value: 12160,
        channel_mix: { table: 4, delivery: 1 },
      },
    ],
    store_daily_metrics: analyticsSeed.dailyMetrics,
    billing_records: [
      {
        id: 'billing_golden',
        store_id: storeA,
        admin_email: 'golden@example.com',
        plan: 'pro',
        setup_status: 'setup_paid',
        subscription_status: 'subscription_active',
        last_payment_at: isoDaysAgo(3, 10),
        next_billing_at: isoDaysAgo(-27, 10),
        payment_method_status: 'ready',
        updated_at: isoDaysAgo(0, 10),
        events: [
          {
            id: 'billing_event_golden_setup',
            store_id: storeA,
            event_type: 'setup_fee',
            title: '초기 세팅비 결제 완료',
            amount: 390000,
            status: 'paid',
            occurred_at: isoDaysAgo(89, 11),
          },
          {
            id: 'billing_event_golden_subscription',
            store_id: storeA,
            event_type: 'subscription_charge',
            title: '3월 구독 결제 성공',
            amount: 79000,
            status: 'paid',
            occurred_at: isoDaysAgo(3, 10),
          },
        ],
      },
      {
        id: 'billing_mint',
        store_id: storeB,
        admin_email: 'mint@example.com',
        plan: 'vip',
        setup_status: 'setup_paid',
        subscription_status: 'subscription_past_due',
        last_payment_at: isoDaysAgo(34, 10),
        next_billing_at: isoDaysAgo(-2, 9),
        payment_method_status: 'action_required',
        updated_at: isoDaysAgo(0, 9),
        events: [
          {
            id: 'billing_event_mint_setup',
            store_id: storeB,
            event_type: 'setup_fee',
            title: '초기 세팅비 결제 완료',
            amount: 490000,
            status: 'paid',
            occurred_at: isoDaysAgo(71, 9),
          },
          {
            id: 'billing_event_mint_failed',
            store_id: storeB,
            event_type: 'payment_failure',
            title: '정기 결제 실패',
            amount: 149000,
            status: 'failed',
            occurred_at: isoDaysAgo(1, 8),
            note: '카드 유효기간 만료로 재시도 필요',
          },
          {
            id: 'billing_event_mint_refund',
            store_id: storeB,
            event_type: 'refund_request',
            title: '환불/해지 문의 접수',
            amount: 149000,
            status: 'requested',
            occurred_at: isoDaysAgo(0, 8),
            note: '운영 중단 여부 검토 요청',
          },
        ],
      },
    ],
    admin_users: [
      {
        id: 'admin_platform_owner',
        profile_id: profileId,
        name: 'Platform Owner',
        email: 'ops@mybiz.ai.kr',
        role: 'platform_owner',
        linked_store_ids: [storeA, storeB, storeC],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(0, 9),
        created_at: isoDaysAgo(60),
      },
      {
        id: 'admin_platform_review',
        name: '리뷰 관리자',
        email: 'review@mybiz.ai.kr',
        role: 'platform_admin',
        linked_store_ids: [],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(0, 8),
        created_at: isoDaysAgo(45),
      },
      {
        id: 'admin_golden_owner',
        profile_id: goldenOwnerProfileId,
        name: '김민준',
        email: 'golden@example.com',
        role: 'store_owner',
        linked_store_ids: [storeA],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(1, 18),
        created_at: isoDaysAgo(92),
      },
      {
        id: 'admin_mint_owner',
        profile_id: mintOwnerProfileId,
        name: 'Lee Doyeon',
        email: 'mint@example.com',
        role: 'store_manager',
        linked_store_ids: [storeB],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(1, 19),
        created_at: isoDaysAgo(75),
      },
      {
        id: 'admin_buffet_owner',
        profile_id: buffetOwnerProfileId,
        name: 'Han Sujin',
        email: 'buffet@example.com',
        role: 'store_owner',
        linked_store_ids: [storeC],
        status: 'active',
        invitation_status: 'accepted',
        last_sign_in_at: isoDaysAgo(0, 10),
        created_at: isoDaysAgo(66),
      },
      {
        id: 'admin_aurora_candidate',
        name: '박서윤',
        email: 'aurora@example.com',
        role: 'store_owner',
        linked_store_ids: [],
        status: 'pending',
        invitation_status: 'scheduled',
        created_at: isoDaysAgo(0, 10),
      },
    ],
    system_status: [
      {
        id: 'system_data_source',
        key: 'data_source',
        label: '현재 데이터 소스',
        value: 'Mock Repository Active',
        status: 'active',
        description: 'mock/local storage 기반 데이터 저장소가 운영 콘솔에 연결되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_gemini',
        key: 'gemini',
        label: 'Gemini 상태',
        value: 'Gemini Fallback Enabled',
        status: 'ready',
        description: 'AI 응답 실패 시 fallback narrative를 사용하도록 준비되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_portone',
        key: 'portone',
        label: 'PortOne 연동 준비 상태',
        value: 'PortOne Billing Pending Integration',
        status: 'pending',
        description: 'billing 탭에서 세팅비/구독/환불 상태를 먼저 운영하고 향후 PortOne 웹훅으로 확장할 예정입니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_public_pages',
        key: 'public_pages',
        label: '공개 페이지 상태',
        value: 'Public Pages Ready',
        status: 'active',
        description: '홈페이지, 요금제, 약관/개인정보/환불 페이지가 공개 라우트로 준비되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_admin_console',
        key: 'admin_console',
        label: '보호 라우트 상태',
        value: 'Admin Console Active',
        status: 'active',
        description: '/dashboard 이하 경로는 보호 라우트로 분리되어 dev 관리자 콘솔로 동작합니다.',
        updated_at: isoDaysAgo(0, 9),
      },
      {
        id: 'system_seed',
        key: 'seed_state',
        label: '최근 배포/시드 상태',
        value: 'Seed Refreshed 2026-03-14',
        status: 'ready',
        description: '스토어 요청, billing, admin users, system status seed가 최신 기준으로 반영되어 있습니다.',
        updated_at: isoDaysAgo(0, 9),
      },
    ],
    store_provisioning_logs: [
      {
        id: 'log_golden_requested',
        request_id: requestGolden,
        store_id: storeA,
        action: 'requested',
        level: 'info',
        message: '골든커피 스토어 생성 요청이 접수되었습니다.',
        created_at: isoDaysAgo(95, 9),
      },
      {
        id: 'log_golden_approved',
        request_id: requestGolden,
        store_id: storeA,
        action: 'approved',
        level: 'success',
        message: '검수 완료 후 운영 스토어로 승인되었습니다.',
        created_at: isoDaysAgo(88, 11),
      },
      {
        id: 'log_golden_store_created',
        request_id: requestGolden,
        store_id: storeA,
        action: 'store_created',
        level: 'success',
        message: 'stores, brand, location, notices, features가 생성되었습니다.',
        created_at: isoDaysAgo(88, 11),
      },
      {
        id: 'log_mint_requested',
        request_id: requestMint,
        store_id: storeB,
        action: 'requested',
        level: 'info',
        message: 'Mint Izakaya 스토어 생성 요청이 접수되었습니다.',
        created_at: isoDaysAgo(78, 9),
      },
      {
        id: 'log_mint_billing',
        request_id: requestMint,
        store_id: storeB,
        action: 'billing_created',
        level: 'success',
        message: '초기 세팅비 billing record가 생성되었습니다.',
        created_at: isoDaysAgo(71, 11),
      },
      {
        id: 'log_north_review',
        request_id: requestNorth,
        action: 'review_started',
        level: 'info',
        message: '브랜드 컬러, B2B 섹션, 멀티매장 운영 범위를 검토 중입니다.',
        created_at: isoDaysAgo(0, 11),
      },
      {
        id: 'log_ember_rejected',
        request_id: requestEmber,
        action: 'rejected',
        level: 'warning',
        message: '사업자 정보 보완 요청으로 반려 처리되었습니다.',
        created_at: isoDaysAgo(2, 16),
      },
    ],
    store_public_pages: [],
  };

  database.store_public_pages = buildSeedStorePublicPages(database);

  return database;
}
