export const queryKeys = {
  stores: ['stores'] as const,
  storeBySlug: (slug: string) => ['stores', 'slug', slug] as const,
  setupRequests: ['setup-requests'] as const,
  dashboard: (storeId: string) => ['dashboard', storeId] as const,
  aiManager: (storeId: string) => ['ai-manager', storeId] as const,
  aiReports: (storeId: string) => ['ai-reports', storeId] as const,
  customers: (storeId: string) => ['customers', storeId] as const,
  reservations: (storeId: string) => ['reservations', storeId] as const,
  schedules: (storeId: string) => ['schedules', storeId] as const,
  surveys: (storeId: string) => ['surveys', storeId] as const,
  waiting: (storeId: string) => ['waiting', storeId] as const,
  orders: (storeId: string) => ['orders', storeId] as const,
  kitchen: (storeId: string) => ['kitchen', storeId] as const,
  storeTables: (storeId: string) => ['store-tables', storeId] as const,
  menu: (storeId: string) => ['menu', storeId] as const,
  brand: (storeId: string) => ['brand', storeId] as const,
  sales: (storeId: string) => ['sales', storeId] as const,
  contracts: (storeId: string) => ['contracts', storeId] as const,
  publicStore: (slug: string) => ['public-store', slug] as const,
} as const;
