export const queryKeys = {
  adminSession: ['admin-session'] as const,
  stores: ['stores'] as const,
  storeBySlug: (slug: string) => ['stores', 'slug', slug] as const,
  setupRequests: ['setup-requests'] as const,
  platformOverview: ['platform-overview'] as const,
  storeRequests: ['store-requests'] as const,
  storeRequestDetail: (requestId: string) => ['store-requests', requestId] as const,
  platformStores: ['platform-stores'] as const,
  platformStoreDetail: (storeId: string) => ['platform-stores', storeId] as const,
  billingRecords: ['billing-records'] as const,
  adminUsers: ['admin-users'] as const,
  systemStatus: ['system-status'] as const,
  provisioningLogs: ['store-provisioning-logs'] as const,
  dashboard: (storeId: string) => ['dashboard', storeId] as const,
  aiManager: (storeId: string) => ['ai-manager', storeId] as const,
  aiReports: (storeId: string) => ['ai-reports', storeId] as const,
  customers: (storeId: string) => ['customers', storeId] as const,
  inquiries: (storeId: string) => ['inquiries', storeId] as const,
  reservations: (storeId: string) => ['reservations', storeId] as const,
  schedules: (storeId: string) => ['schedules', storeId] as const,
  surveys: (storeId: string) => ['surveys', storeId] as const,
  waiting: (storeId: string) => ['waiting', storeId] as const,
  orders: (storeId: string) => ['orders', storeId] as const,
  tableLiveBoard: (storeId: string) => ['table-live-board', storeId] as const,
  conversationSessions: (storeId: string, inquiryId?: string) =>
    ['conversation-sessions', storeId, inquiryId || 'all'] as const,
  conversationMessages: (sessionId: string) => ['conversation-messages', sessionId] as const,
  kitchen: (storeId: string) => ['kitchen', storeId] as const,
  storeTables: (storeId: string) => ['store-tables', storeId] as const,
  menu: (storeId: string) => ['menu', storeId] as const,
  brand: (storeId: string) => ['brand', storeId] as const,
  sales: (storeId: string) => ['sales', storeId] as const,
  operationsMetrics: (storeId: string) => ['operations-metrics', storeId] as const,
  contracts: (storeId: string) => ['contracts', storeId] as const,
  publicStore: (slug: string) => ['public-store', 'slug', slug] as const,
  publicStoreBySlug: (slug: string) => ['public-store', 'slug', slug] as const,
  publicStoreById: (storeId: string) => ['public-store', 'id', storeId] as const,
  platformAdminSession: ['platform-admin-session'] as const,
  platformAdminOverview: ['platform-admin-overview'] as const,
  platformAdminResource: (resource: string) => ['platform-admin-resource', resource] as const,
  platformPaymentTests: ['platform-payment-tests'] as const,
  platformContentQuality: ['platform-content-quality'] as const,
  publicPlatformHomepage: ['public-platform-homepage'] as const,
  publicPlatformPricing: (testPayment?: string | null) => ['public-platform-pricing', testPayment || 'default'] as const,
  publicPlatformChrome: (pathname: string) => ['public-platform-chrome', pathname] as const,
  publicPlatformAnnouncements: ['public-platform-announcements'] as const,
  publicPlatformBoardPosts: ['public-platform-board-posts'] as const,
  publicPlatformPage: (slug: string) => ['public-platform-page', slug] as const,
  publicSurvey: (storeId: string, formId: string) => ['public-survey', storeId, formId] as const,
  publicInquiry: (storeId: string) => ['public-inquiry', storeId] as const,
  publicConsultation: (storeId: string) => ['public-consultation', storeId] as const,
} as const;
