import {
  BarChart3,
  Bell,
  Bot,
  Calendar,
  CheckCircle2,
  ChevronLeft,
  ChevronRight,
  ClipboardList,
  Clock3,
  FileText,
  Globe,
  LayoutDashboard,
  Menu,
  MessageSquare,
  Search,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Store,
  TableProperties,
  Truck,
  Users,
  UtensilsCrossed,
  WandSparkles,
  X,
} from 'lucide-react';

export const Icons = {
  AI: Bot,
  Alert: Bell,
  Apps: Sparkles,
  ArrowLeft: ChevronLeft,
  ArrowRight: ChevronRight,
  Brand: ShieldCheck,
  Calendar,
  Chart: BarChart3,
  Check: CheckCircle2,
  Clock: Clock3,
  Contract: FileText,
  Dashboard: LayoutDashboard,
  Delivery: Truck,
  Globe,
  Kitchen: UtensilsCrossed,
  Menu,
  Message: MessageSquare,
  Mobile: Smartphone,
  Reservation: Calendar,
  Search,
  Settings,
  ShieldCheck,
  Store,
  Survey: ClipboardList,
  Table: TableProperties,
  Users,
  Waiting: Clock3,
  Zap: WandSparkles,
  X,
};
