import React from 'react';
import { 
  LayoutDashboard, 
  Users, 
  Calendar, 
  ClipboardList, 
  TrendingUp, 
  Truck, 
  MessageSquare, 
  ShieldCheck, 
  FileText, 
  Clock,
  Bell,
  Settings,
  Search,
  ArrowRight,
  Zap,
  Bot,
  CheckCircle2,
  AlertCircle,
  BarChart3,
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  Star,
  Smartphone,
  Globe
} from 'lucide-react';

export const Icons = {
  Dashboard: LayoutDashboard,
  Users,
  Calendar,
  Survey: ClipboardList,
  Growth: TrendingUp,
  Delivery: Truck,
  Brand: ShieldCheck,
  Contract: FileText,
  Waiting: Clock,
  Clock,
  Notification: Bell,
  Settings,
  Search,
  ArrowRight,
  Zap,
  AI: Bot,
  Check: CheckCircle2,
  Alert: AlertCircle,
  Chart: BarChart3,
  Menu,
  X,
  ChevronRight,
  ChevronLeft,
  Star,
  Mobile: Smartphone,
  Globe,
  Message: MessageSquare
};
